### ISSUE TITLE
Question: Tracking only Apple Watch (iPhone left home)

### ISSUE THREAD

**Issue by tom-roger** [gcobb321/icloud3#103]
Hi,

First: Thank you for developing this great application. Really enjoy it!

My kids both have Apple Watch with 4G. They leave their iPhone's at home most of the time. I use both their iPhone and Apple Watch device trackers for their person entity. This leads to status being set to "Home" from time to time since their phone is left home. How can I avoid this?

I also notice that the update rate for their Apple Watch device tracker is set to 2 hours (default). This does not update even if their location changes (iPhone left at home). I have manually set the update rate for the Apple Watch to every 30 min. Is this the correct way of doing it, or am I missing something?

Appreciate your help with this.

Best regards,
Tom-Roger (Norway)

**Comment by gcobb321** [comment]
iCloud3 tracks devices, not people. By combining two devices (phone and watch). I would suspect HA considers the person Home when one device is Home, not both devices. I would think the only way to avoid your problem would be to not have HA combine them but create your own binary_sensor where you would set the Home/Away status to Home if both devices being Home or Away if one device is Away in an automation or script.

The watch is probably being set to a 2-hour interval because it is considered to be in a zone (Home). iCloud3 relies on the iOS App to issue a zone enter/exit trigger. If the iOS app in not on the device, it will not get a trigger and will update the device location at the next interval (the 2-hours). I suspect the iOS App is not on the watch. Or if it is, it is not doing the same kind of location processing that is done on the phone.
