### ISSUE TITLE
Installing via HACS Doesn't Add a Repository for iCloud3

### ISSUE THREAD

**Issue by lordexorr** [gcobb321/icloud3#106]
When installing iCloud3 via HACS everything seems to install normally, however, it doesn't add an iCloud3 Repository to the HACS Integrations page like other HACS integrations do. Screenshot below.

![image](https://user-images.githubusercontent.com/38336945/104379915-28ea5300-54f8-11eb-9c3b-a2599d679f0e.png)

**Comment by townsmcp** [comment]
For me, I can see this in HACS:
<img width="630" alt="image" src="https://user-images.githubusercontent.com/14061617/104464244-9c4c9d00-55aa-11eb-81fc-eb36452574da.png">
However my issue is the Lovelace resources didn't have the iCloud integration and even after I have added the entry to resources and setup the config files, reboot and I still can't load iCloud3.
@lordexorr what version are you running of HA?

**Comment by lordexorr** [comment]
I'm using 2021.1.1. Screenshot below just to give you full info though.

![image](https://user-images.githubusercontent.com/38336945/104469745-d7d57000-5586-11eb-9856-451718740de3.png)

OS I'm using (latest stable release of HASS) screenshot below as well in case it helps you.

![image](https://user-images.githubusercontent.com/38336945/104469845-f8052f00-5586-11eb-8b13-ec0f356daa31.png)

What are the errors your getting in the home-assistant.log on boot that relate to iCloud3? I had a few issues when I first setup, that I was able to flush out based on the log file on HA start.

**Comment by lordexorr** [comment]
@townsmcp In addition to my post above, paste your current config setup for iCloud3 in the configuration.yaml file (black out the username/password field of course) and I'll try to see if I can see what's going on. As a comparison, below is my current configuration.yaml file.

IMPORTANT (and this may want to be added to the documentation): If your iCloud password includes ! or other various symbols you will need to put quotes around the password. Example - password: "!icloudpassword!". If you don't put quotes, it will confuse HA and it won't read the password right and you won't be able to authenticate.
```

#iCloud3 Device Tracker Integration
device_tracker:
  - platform: icloud3
    username: icloudaccount
    password: icloudpassword
    tracking_method: famshr
    config_ic3_file_name: config_ic3.yaml
```

**Comment by gcobb321** [comment]
HACS will only install a custom component in one place. It will not install iCloud3 in the custom_components directory and the Event Log Lovelace card where it needs to go at the same time, unfortunately. Because of that,, iCloud3 checks the /config/www/custom_cards directory when it loads and moves the icloud3-event-log-card.js to the custom cards directory then. You have to start iCloud3 first before the resource can be a set up, set the resource up, then restart HA to finish setting up the Lovelace Event Log. I’ll look at the docs to see it it can be explained better. 

Also, in the config above, the tracking_method is not needed unless you are using only the iosapp  and the config_ic3_file_name defaults to config_ic3.yaml.

**Comment by townsmcp** [comment]
@lordexorr thanks for that about passwords containing special characters.
@gcobb321 I think the quotes was the issue for me

**Comment by lordexorr** [comment]
The repo is showing normally after the HA upgrade today (and re-install of iCloud3 after). I think this can be considered resolved.
