### ISSUE TITLE
Sometimes a device from family sharing is missing

### ISSUE THREAD

**Issue by lexieke** [gcobb321/icloud3#112]
Hi @gcobb321 

First of all thanks for all the hard work, much appreciated! 

For security reasons I'm tracking all devices through an additional account so if someone would ever have access to the cookies or secrets file, my iClould devices are not breached.

When I restart the icloud3 integration, I can see that sometimes a device from familysharing is "missed" in the overview causing icloud3 to state that it cannot track some devices. After restarting one a few times, the device reappears and it is picked up.

Is this a bug? Anything I can do in parameters?

**Comment by gcobb321** [comment]
When iCloud3 starts, the first thing it does is ask for the device info from iCloud, goes through what was returned and lists them. If the device is not in the list then it was not in the data iCloud returned. It is probably a timing issue with iCloud since it has to locate all the devices before it returns the data. Once everything is up and running, if a location is old, iCloud3 requests the location again. 

You can refresh the list using the Event Log > Actions >Restart iCloud3. That will refresh everything and you don’t have to restart HA

**Comment by lexieke** [comment]
Thanks @gcobb321 for your quick feedback. The problem is that if they device is missed due to the timing issue, it won't be tracked until it is noticed. I guess I can overcome that by doing an automation that checks if the latest update > 1d for example.
