### ISSUE TITLE
"Outside Zone and No Exit Zone Trigger" happens often

### ISSUE THREAD

**Issue by eafarris** [gcobb321/icloud3#117]
As I understand it, iCloud3 relies on the iOS app to trigger an exit, and if iCloud3 sees the phone outside the zone, but didn't get a trigger, it considers that false data. However, this event in the iCloud3 log happens often when the phone is actually away. This is probably because the app isn't running and no longer in the background on the target device. iOS has suspended it and it doesn't get updates anymore. Is this right?

Is there a way to tell iCloud3 to update the location of the device regardless of it not hearing a trigger from the companion app, to force it to consider a location change as legitimate? And is this something I could automate?

**Comment by gcobb321** [comment]
You are correct that iCloud3 will discard a location update if it is outside of the zone and has not received an Exit trigger. However, it also looks at the 'ZoneRadius+GPSAccuracyThreshold' distance. 

```
zone_radius_accuracy = ZoneRadius (from the Zone setup) + GPSAccuracyThreshold (gps_accuracy_threshold config parm)

if the distance from the zone < zone_radius_accuracy:
     - Location is outside of the zone but less than the zone radius + zone radius accuracy
     - Keep the phone in the zone. The location is outside of the zone but inside the zone accuracy limit
     - Display the message - "Outside Zone and No Exit Zone trigger, Zone-{zone}, Keeping in zone > {distance},
                    DiscardDist-{zone_radius} to {zone_radius_accuracy}

if the distance from the zone >= zone_radius_accuracy:
     - Location is beyond the zone radius + the zone radius accuracy
     - Assume a missed exit trigger and move the device outside of the zone
     - Display the message - "Outside Zone and No Exit Zone trigger but outside threshold, Zone-{zone}, 
                    DiscardDist-{zone_radius} to {zone_radius_accuracy}
```
To keep the zone exit even though you didn't get an Exit trigger, you will have to reduce threshold size by reducing the gps_accuracy_threshold config parameter. But that might lead to other location events being discarded because of the gps accuracy.
