### ISSUE TITLE
Typo in version 2.3.2

### ISSUE THREAD

**Issue by ajw107** [gcobb321/icloud3#119]
This error is all over my log (you've mistypes a double quote instead of a single):
```
  File "/config/custom_components/icloud3/device_tracker.py", line 25
    VERSION = '2.3.2"
                    ^
SyntaxError: EOL while scanning string literal
```

**Comment by gcobb321** [comment]
The fix was been uploaded about 2 hours ago. Reinstall iCloud3 using HACS.

**Comment by ajw107** [comment]
Hmm, I had literally just upgraded it a few minutes before I sent the message.  Also just tried to reinstall it again a few minute ago, and the same issue is there (I can just edit the file to stop the error).  not sure why I'm not seeing any newer version than 2.3.2 (refreshed, deleted cache and re-logged in, etc and still showing 2.3.2 and upon install the same bug).

**Comment by gcobb321** [comment]
I just checked the files in the iCloud3 repository and think one of them was not updated correctly on GitHub even though it showed everything was updated correctly. The one on the Releases tab was correct but the one in the root directory was not, even though they had the same date and time.

I forced an update to make sure everything matches and updated the Releases tab a little differently to make sure the correct version was there.

Try a HACS again and see if it works and gets the new file rather than the old one (do a reinstall). The other option is download the icloud3.zip file [here](https://github.com/gcobb321/icloud3/blob/v2.3.2/icloud3.zip) and unzip the device_tracker.py file into the icloud3 directory. Or just unzip everything into the icloud3 directory.

Hopefully, that will fix it and you will have the latest and correct version. The v2.3.2 update has been downloaded 3 times and I can not tell it is the latest one since it only displays the counts by day, not by time. Let me know if I need to check on anything else.

**Comment by pauly7300** [comment]
I'm in the same boat.  Tried reinstall with Hacs 10 mins ago and it's still isn't loading correctly.  I just downloaded from the zip you included in the last comment and it has 2.3.1 in line 21 of the pyicloud_ic3.py file.

**Comment by gcobb321** [comment]
The v2.3.1 in pyicloud_ic3.py is ok. iCloud3 is the device_tracker.py file

**Comment by pauly7300** [comment]
ok, but it's still not working after reload from HACS.  I guess i'll try a manual install next.  Not sure if this helps but i'm seeing this in the log. 
Logger: frontend.js.latest.202012291
Source: components/system_log/__init__.py:193
First occurred: 5:13:04 PM (4 occurrences)
Last logged: 5:14:11 PM

https://*****.duckdns.org:8123/local/custom_cards/icloud3-event-log-card.js?v=1.000:1541:71 Uncaught TypeError: Cannot read property 'attributes' of undefined
https://*****.duckdns.org:8123/local/custom_cards/icloud3-event-log-card.js?v=1.000:1429:75 Uncaught TypeError: Cannot read property 'attributes' of undefined

**Comment by gcobb321** [comment]
I just did a HACS update to verify everything again and now can not get icloud3 running. I keep getting a HA error saying it can not load the device_tracker module from the ‘custom_components/icloud3 v2’ directory which has not existed for months. I have no idea what HACS did, where it is getting the ‘iCloud v2’ and will probably end up restoring from a backup tomorrow. 

Let me know if iCloud3 loads. If not, I may have to pull the release before anyone else has this error.

**Comment by pauly7300** [comment]
Well, I went back into device_tracker.py one more time before manual install and noticed the single double quote on line 25.  
VERSION = '2.3.2"

I changed the quote and it's running again now.

**Comment by gcobb321** [comment]
Just restored the HA configuration and then did a HACS update. V2.3.2 was installed correctly. There must be some type of caching or timing issue somewhere. Sometimes restarting the RPi running HA solves this issue.

**Comment by gcobb321** [comment]
Glad you got it running. Sorry for the problems with the update. I was in a hurry and didn’t restart ha and reload icloud3 after changing the version number before issuing the release. My wife was getting a Moderna #2 shot and I had to leave.

**Comment by pauly7300** [comment]
Gary, that's great to hear she's getting her 2nd.  Mine is in 3 weeks.  Moderna #1 last week for me.

**Comment by jeffs1212** [comment]
Just updated through HACS and had the same issue, but the fix to the device_tracker.py file corrected the problem, (thanks to those that found this so quick).  Just a nit, but the "actions" dropdown in the log card still says v2.3.0, the log itself correctly notes v2.3.2. @gcobb321 you got you priorities straight - thank you for all your great work here!

**Comment by jwl17330536** [comment]
Yes, my device_tracker.py was also incorrect in version 2.3.2.  I reinstalled, reinstalled and rebooted, and then ultimately just changed the file by hand:

custom_compoments/icloud3/device_tracker.py 
from:
``` VERSION = '2.3.2" ```
to: 
``` VERSION = "2.3.2" ```

Restart home assistant and voila.
