### ISSUE TITLE
The 2.3.4 version parameter does not translate to the locale

### ISSUE THREAD

**Issue by a120578270** [gcobb321/icloud3#126]
display_zone_format: fname
![image](https://user-images.githubusercontent.com/58241282/108799667-d5295a00-75cb-11eb-88c7-6fed94da4ee6.png)

**Comment by gcobb321** [comment]
I’m not sure what you mean. I don’t think there have been any changes to that since v2.3 was released.

**Comment by a120578270** [comment]
Before, the position will be displayed in Chinese, but after updating 2.3.4, there is a problem!  GONG_SI should be displayed as "公司" instead

**Comment by gcobb321** [comment]
iCloud3 does not do any translation. It uses the zone name and friendly name returned by HA. You may want to go back to an earlier version to help determine where the translation problem is coming from.

**Comment by a120578270** [comment]
I haven't changed my HA version. This problem occurred when iCloud3 was upgraded from 2.3.3 to 2.3.4. This problem also occurred in around 2.1! If, as you say, it is displayed by the zone name of HA, that is iCloud3's problem.
![image](https://user-images.githubusercontent.com/58241282/108852790-fcf6dd00-7620-11eb-8b33-c4bee9a8a7e8.png)

**Comment by a120578270** [comment]
![image](https://user-images.githubusercontent.com/58241282/108853489-bf468400-7621-11eb-8d1c-a1ffe890e7ec.png)
All displays on the zone side of HA are normal!

**Comment by a120578270** [comment]
![image](https://user-images.githubusercontent.com/58241282/108854934-62e46400-7623-11eb-95bf-783bf6b983b3.png)
Switching back to 2.3.3 is fine, none of the parameters have changed!

**Comment by gcobb321** [comment]
Does it work correctly if the `display_zone_format: fname` paraqmeter is in *configuration.yaml* instead of *config_ic3.yaml*?

**Comment by a120578270** [comment]
display_zone_format: fname is configured in cconfiguration.yaml
All of my Settings have not changed, which is normal in 2.3.3, but it is now in 2.3.4.

**Comment by gcobb321** [comment]
I think I found the problem with the fname handling. Basically, fixing one problem - allowing *track_from_zone* friendly zone name specification reverted the fname setup and reintroduces a setup problem corrected in v2.3.1.

I'm thinking about changing the zone sensor names so they better match the Configuration >  Zone >Name. Currently:
- Configuration > Zone > Name = iC3 zone_fname (friendly name)
- iC3 zone_name is a reformatted zone entity name

I now think:
- iC3 zone_name = Configuration > Zone > Name. 
- iC3 zone_fname = Goes away since it would be the iC3 zone_name

This only effects zone names with multiple words. In your case, it is *jin_xian_jia_yuan*. A single word zone entity (Home, Work) and Name (Home, Work) create the same value.

Right now, the sensors are:
- zone_name - JinXianJiaYuan (from zone entity, remove the '-', capitalize the first letter)
- zone_fname - Jin Xian Jia Yuan (from zone Name field, ok in v2.3.3, wrong in v2.3.4)
- zone_title - Jin Xian Jai Yuan (from zone entity, change '_' to space, capitalize first letter)
The iOS App uses the zone's Name, which is the iCloud3 friendly name.

The new way would make the iCloud3 *sensor.zone_name* the same as the zone's Name and the same as the iOS App zone's name. The *sensor.zone_fname* would be removed.
New way:
- zone_name - Jin Xian Jia Yuan (from zone Name field,))
- zone_sname - JinXianJiaYuan (from zone entity, remove the '-', capitalize the first letter)
- zone_title - Jin Xian Jai Yuan (from zone entity, change '_' to space, capitalize first letter)

- zone_fname --> zone_name
- zone_name --> zone_sname (`sname` for short name)
- zone_title --> zone_title (or do you think `lname` for long name is more consistant)

The default would be the zone_name

I would appreciate your thoughts.

**Comment by gcobb321** [comment]
v2.3.5 is available for testing in the GitHub development v2.3.5 directory
Download the zip file here
Unzip it into the icloud3 directory
Restart HA
It fixes the following bugs:

The location_isold error when the data is not available. This was obsolete and unused code that has been removed.
Fixed the problem with the zone’s friendly name created in the v2.3.4 update for zones with multiple words.

**Comment by a120578270** [comment]
Thank you very much for your repair. Due to my poor English, I may have some problems in communication, which may bring inconvenience to you. Please understand! The test of version 2.3.5a is normal, thank you again!

**Comment by gcobb321** [comment]
Glad it’s working again.I appreciate your help finding the problem and testing iCloud3 to make sure it is working correctly.. I’ll be updating HACS after I remove the debug code that is in the v2.3.5a. Let me know if you find something else. And your English is fine
