### ISSUE TITLE
Zone interval frequency 

### ISSUE THREAD

**Issue by naseemr** [gcobb321/icloud3#13]
Hi Gary, 
When near home the interval changes to only 3min. Shouldn’t this change to 15sec?
![60EC7A8B-9FFF-45D1-A8F7-195DD5C67995](https://user-images.githubusercontent.com/3306597/70857868-f963b400-1ebb-11ea-9aff-7e4a56221676.jpeg)

**Comment by broyuken** [comment]
Mine hasn’t been updating fast enough either as of late.

**Comment by gcobb321** [comment]
The next polling time interval is based on a series of tests and when it is set, it stops with that value. The last part of the iCloud3 documentation [here](https://gcobb321.github.io/icloud3/#/chapters/9-tech-info) describes this. It’s probably not completely up to date but will give you an idea of how it works. 

When you exit a zone, the interval is set to 3 minutes to give iCloud3 enough time to figure out what direction you are going. The zone exit test is before the distance from home test So, in your situation, it used the  3-minute time to determine when the next poll should be and never used the distance from home, which would have set it to 15-seconds. 

- At 23:35:20, you were in a stationary zone 8.94mi from home. 
- 5 minutes later at 23:40:45, the state changed from stationary to not home which triggered the update, taking it out of the stationary zone and setting the interval to 3 minutes. 
- But, at that time, you were .3mi from home. That means you were going 112mph to get from the stationary zone to home which is either unrealistic or you are a really good driver. 

What’s missing is a ‘Zone Exit’ trigger from the iOS app that would have taken you out of the stationary zone when it really happened. If it had,  the 3 minute interval would have been set a lot further from home and the distance from home would determine the next interval, which would get smaller as you approached home down to the 15-second time. 

Then the question is did the iOS app issue the trigger or did iCloud3 miss it. The iOS app event log would show the Geographic Zone Exit trigger if there is one. I have seen  the iOS app  throw them away if the gps accuracy was really bad and never issue one. iCloud3 tries to compensate for this but you were too close to home for this to happen. 

To get more detailed info on  what iCloud3 is doing, use the ‘log_level’ configuration parameter [described here](https://gcobb321.github.io/icloud3/#/chapters/2-config-parms?id=zone-interval-and-sensor-configuration-items).  Additional entries are made to the  iCloud3 Event Log and a lot more are added to the HA log file.

**Comment by broyuken** [comment]
My wife just left a stationary zone, confirmed by checking the actual FMF app but icloud3 still shows her as stationary. 

How do I view the event log? I looked in the log book but don’t have anything called geographic zone exit

**Comment by gcobb321** [comment]
To check the iOS app Event Log, go to HA Sidebar>App Configuration >Event Log. Scroll through the items looking for Location Update items. It shows the zones it is monitoring and the activity for the different zones. This includes Geographic Zone Exit triggers it has issued. If you don’t see any or it shows gps accuracy errors, than no Zone Exits were issued by the iOS app. iCloud3 depends on Zone exits being issued by the iOS app to know what to do. If it doesn’t receive them, than there is nothing iCloud3 can do and the device will stay in the zone until the next update time.

**Comment by broyuken** [comment]
Just exported the events but it looks like they don't keep long enough. The logs are only for today, gonna have to see if I can pull them quickly next time I go into/out of a stationary zone.

Edit: Just went on to her phone and I don't see an zone exit trigger, I only see a significant change event about 10 minutes after she left.

**Comment by gcobb321** [comment]
What version of the iOS app and iCloud3 are you using?
Have you gone into the iOS app forum to see if others are having the same issue?
Try turning off using the stationary zone by using ‘stationary_still_time: 999’ configuration parameter to see what happens. 
Do you get Geographic Zone Exit triggers when you leave Home?
Get more detailed info in the iCloud3 Event Log using the ‘log_level: debug’ configuration parameter. It will show everyiOS app trigger change and state change.

**Comment by broyuken** [comment]
I'm using iOS 2.0.0 (69) from the official app store, not the beta and icloud3 2.0.5 from hacs. I get geographic exit triggers when I leave home and other defined zones, but for some reason stationary was not working. I will try the debug change and report back.

**Comment by broyuken** [comment]
I just had an issue where I was .53 miles from home and was on the 15 second interval, then it switched to .37 miles away and a 3 minute interval. What would cause that to happen? It looks like it thought I was home, then went to the 3 minute interval to see if I was going towards or away from home. What would cause that to happen? Was it just bad GPS data?

![image](https://user-images.githubusercontent.com/1593391/71095886-5e98fd00-217b-11ea-9bba-482ea8881ae9.png)

**Comment by gcobb321** [comment]
Probably not gps accuracy since distances look correct. Got a Significant Location Update while in the 15-second close to Home check which probably reset how the interval was being calculated. The last part of the iCloud3 documentation [here](https://gcobb321.github.io/icloud3/#/chapters/9-tech-info?id=how-the-interval-is-determined) discussed how the interval is calculated.  There have probably been some minor changes but it is complicated and tries to handle every situation. One trigger on top of another effects the result. The 'State Change' at the same time also effects what is going on. The ‘log_level: interval' parameter displays a code the tells how the calculation was done and is shown in the dabbler in the docs.

**Comment by naseemr** [comment]
I created near_zone to make the interval shorter but still at 3min.

**Comment by gcobb321** [comment]
All near_zone does is to create a zone that will wake up the iOS app if there are gps accuracy in your area and to get it to send a Geographic Zone Enter& Exit trigger that might then start the polling based on the distance and timing.

 In order to see/explain how the interval is calculated, a lot more info is needed. The only way to get that info is to use the log_level config parameter with debug and interval to select what you want to display. Then you need to refer to the documentation with the interval selection code to see what it means. Then you need to look at gps accuracy and if the location is old to see how that effects the selection. Then you need to look at the iOS app triggers and the next update time to see if there are several things going on at the same time. You then need to determine if the interval calculation is not correct only once or all the time in that situation. 

There could be tweeks to the calculation that I needed to make but usually I cannot  duplicate your individual situation and cannot tell if it is a coding problem or something else and, if I change the code, if it is fixed or not on my end. Plus, one change early in the interval test can effect messing up something that should have been caught later on. 

I'll try to go back through the code and make sure the interval selection code matches what is really going on but it is pretty close now. 

The last part of the iCloud3 documentation [here](https://gcobb321.github.io/icloud3/#/chapters/9-tech-info?id=how-the-interval-is-determined) discussed how the interval is calculated.
The log_level parameter is described [here](https://gcobb321.github.io/icloud3/#/chapters/2-config-parms?id=zone-interval-and-sensor-configuration-items).

Feel free to look at the code if you want. It's done in the '_determine_interval' function of 'device_tracker.py' Program.

**Comment by naseemr** [comment]
I was never able to get interval to 15 sec. I am using tracking method iOS app.
