### ISSUE TITLE
Error updating Watch location - EVA_Notice is not defined

### ISSUE THREAD

**Issue by jayscovill** [gcobb321/icloud3#137]
I'm seeing the below error in the logs when trying to update my Watch location.  

![image](https://user-images.githubusercontent.com/30603659/110813611-a7444680-8256-11eb-82f1-82f6f07f1071.png)

Does that look familiar to anyone?

**Comment by gcobb321** [comment]
The EVA_NOTICE is an unknown variable name. It should be EVLOG_NOTICE. It will be fixed in the v2.3.6b3 beta release in the icloud3 development directory. The error it was describing is the 'An error occurred sending a location request' to the watch. 

I have never tried sending a location/notification to the watch so really do not know if it is possible. I'd appreciate it if you would review the ios app documentation to see if it can be done.

**Comment by jayscovill** [comment]
Thanks Gary,

My watch location isn't updating.  Is that related to this error then?

**Comment by gcobb321** [comment]
Probably but I've never tracked a watch, only a phone and ipad.

**Comment by jayscovill** [comment]
Gotchya, it mentions it can track Watches in the description. Let me know if there is anything I can do to help test that as that's my main use case.

Edit: [This](https://stackoverflow.com/questions/47543655/request-location-on-the-apple-watch-only-without-code-on-the-paired-phone) post seems to indicate it's possible as of WatchOS 6/Xcode 11 but I can't find any more supporting information.

**Comment by gcobb321** [comment]
iCloud3 v2.4.0 was just uploaded to HACS.
