### ISSUE TITLE
ic3 location not updating

### ISSUE THREAD

**Issue by Snuffy2** [gcobb321/icloud3#139]
I'm not sure what I may be doing wrong, but my ic3 location doesn't seem to be updating even though the HA iOS App location is updating (see screenshot)
![SNAG-0095](https://user-images.githubusercontent.com/6526076/111166820-e506df00-8576-11eb-8817-9418bb9fcce8.png)
![SNAG-0096](https://user-images.githubusercontent.com/6526076/111167401-78401480-8577-11eb-9c92-a0121ae5e5de.png)
![SNAG-0097](https://user-images.githubusercontent.com/6526076/111167290-56df2880-8577-11eb-800a-bbf6ee0272a1.png)

**Comment by gcobb321** [comment]
It looks like there was no Zone Exit trigger picked up by iC3 to take iC3 out of Home. You issued the Locate Device command but that was not picked up either. It shows the command being issued and being sent several times (#0 & #1), which should get the ios app to issue a manual location trigger but it did not.

I just added a Troubleshooting chapter to the iC3 docs [here](https://gcobb321.github.io/icloud3/#/chapters/1.8-troubleshooting-problems?id=the-phone-does-not-go-to-an-away-state-when-you-exit-a-zone). That might help pinpoint where the problem is.

**Comment by gcobb321** [comment]
iCloud3 v2.4.0 was just uploaded to HACS.
