### ISSUE TITLE
An update to iCloud3v2.4.0 found an error in the location of the device and showed it to be at home

### ISSUE THREAD

**Issue by a120578270** [gcobb321/icloud3#142]
![image](https://user-images.githubusercontent.com/58241282/114118642-b41e8d80-991b-11eb-8440-dff427687794.png)
![image](https://user-images.githubusercontent.com/58241282/114118658-bed92280-991b-11eb-8a1e-b933dab9d461.png)
![image](https://user-images.githubusercontent.com/58241282/114118676-c7c9f400-991b-11eb-98dd-28936aafff94.png)
![image](https://user-images.githubusercontent.com/58241282/114118707-d44e4c80-991b-11eb-9488-f0d3756d4022.png)
![image](https://user-images.githubusercontent.com/58241282/114118747-e03a0e80-991b-11eb-8077-77a470f59685.png)

The actual location should be in the company, and it was normally displayed in the company again 20 minutes later, that is, the next update time. This has happened several times before, and the first error after HA restarted was displayed in Home!

**Comment by gcobb321** [comment]
When iCloud3 starts, it puts the phone into the home zone because it has to put it somewhere. Looking at the event log, the location updates were discarded due to poor gps. Then there were some other location error messages and  it then got good location information and updated with the good data. If the location info is bad, the gps accuracy is poor or the information is old, there is not much iCloud3 can do except keep retrying. 

Sometimes the Event Log > Actions > Resume Polling will refresh the location and iCloud3 will get good data.

**Comment by a120578270** [comment]
> When iCloud3 starts, it puts the phone into the home zone because it has to put it somewhere. Looking at the event log, the location updates were discarded due to poor gps. Then there were some other location error messages and it then got good location information and updated with the good data. If the location info is bad, the gps accuracy is poor or the information is old, there is not much iCloud3 can do except keep retrying.
> 
> Sometimes the Event Log > Actions > Resume Polling will refresh the location and iCloud3 will get good data.

Hello, now the question is can iCloud3 keep trying to get the location if the GPS is weak? I'd rather stay in the NotSet state until I get the location right, than try for a while and then incorrectly select home, which will cause my home scene to execute incorrectly!
