### ISSUE TITLE
customize.yaml

### ISSUE THREAD

**Issue by broyuken** [gcobb321/icloud3#15]
It doesn’t seem like these entities are compatible with customize.yaml. I’m trying to rename the travel time sensors to display on a card but it throws an error saying that customize.yaml is not included in my configuration.yaml. It is though and I can edit other entities with it just fine. Just not yours.

**Comment by gcobb321** [comment]
The sensors iCloud3 creates are not in the entity registry but are created when HA starts. It is done this way to be able to create sensors based on the devicename of the devices being tracked and to be able to include or exclude specific sensors.

Rather than changing their names in the entity registry, you can set it to the name you want to display in the ui-Lovelace.yaml configuration file.

————————
Gary Cobb

**Comment by broyuken** [comment]
Hi Gary,

Thank you for the explanation, however I don’t use the Lovelace.yaml config file, I use the GUI and I use the auto entities card to include these dynamically based on if they are set to null or not. Because of that, I don’t think it would be possible for me to change the name of the sensors in the GUI unless there is another way to do it. 

https://github.com/thomasloven/lovelace-auto-entities

![F4C16DB7-3380-4357-893D-290B24444F96](https://user-images.githubusercontent.com/1593391/71253936-4b12a100-22f7-11ea-8bd6-0ae8918d26bc.png)

**Comment by gcobb321** [comment]
I’m not familiar with that so I can’t help with exactly what you need to do.

A couple of suggestions ... Have you looked into setting up a template sensor that takes on the value of the iCloud3 sensor you want to display? Many of the iCloud3 sensors are set to the value of device tracker attributes. If a template sensor doesn’t work, maybe using the device tracker attribute would.

**Comment by broyuken** [comment]
I can look into those, great ideas thank you!

**Comment by broyuken** [comment]
template sensor worked great, thank you!
