### ISSUE TITLE
Prevent icloud3 sensors from being stored in the recorder (history, and logbook)

### ISSUE THREAD

**Issue by jcollas** [gcobb321/icloud3#16]
I've noticed that a huge part of my HA history/logbook is updates from icloud3 device sensors.  Is there any way to exclude them from being recorded by HA?

**Comment by gcobb321** [comment]
I haven't tried it but take a look at the History configuration parameter [here](https://www.home-assistant.io/integrations/history/). Also, Google "exclude sensor from Home Assistant history". Several methods are displayed. I don't know if they will work since the iCloud3 sensors are not in the entity registry but created when iCloud3 loads.

**Comment by jcollas** [comment]
Discovered the create_sensors/exclude_sensors configuration keys.  This does what I want, thanks!
