### ISSUE TITLE
Feature request: unique-id's for all entities 

### ISSUE THREAD

**Issue by groenmarsmannetje** [gcobb321/icloud3#192]
Please generate unique-id's for all entities so that all the entities that are created by this integration can be customized from the user interface.

Especially now that the "old" customization option has been moved to yaml only, this has become essential to keep these things maintainable for basic users. 

This will also offer the opportunity to:
- adjust names (not everybody use English...)
- disable/enable entities from the user interface itself
- set/adjust pictures and icons

It will help to simplify the yaml configuration 

Side note:
The documentation of this integration is impressive. But I always have the feeling that the reason that it needs so much explanation and documentation is a signal in itself that there is room for improvement: simplification and less documentation is probably the key to success for most users.

**Comment by gcobb321** [comment]
Thanks for the request. Doing that requires a complete rewrite of iCloud3 to turn it into a true integration that is added and configured on the HA Configuration > Integrations screen. I have been working on this since last April and hope to have it done in the next few months.  

Regarding the documentation, iCloud3 does a lot and parts of it require explanation on how to set it up and use it, especially the device naming requirements between iCloud3, iCloud and the iOS App. This has been simplified with online configuration capabilities since data can be validated when it is entered. 

I would welcome the help reviewing the documentation and testing iCloud3 v3 when it is available.

**Comment by groenmarsmannetje** [comment]
Happy to help you with that as soon as it is available

**Comment by gcobb321** [comment]
I hope to have v3 in beta in November. I'm working on the docs and v3 looks pretty good on my devices. I'll let you know when it's available.
