### ISSUE TITLE
Dir_of_travel

### ISSUE THREAD

**Issue by bryeartem** [gcobb321/icloud3#20]
Does not seem to be being set to stationary (over an hour at location only .48 miles away, and driving flag did get turned off) nor does the stationary zone seem to change coordinates.  I know you are about to do another update so if this may be fixed in that feel free to just close this.  Thanks again! Working excellent so far!

**Comment by gcobb321** [comment]
Right now, you must be move than 3km (2 mi) from home before a stationary zone is set up. My thinking was if you are getting poor gps around home, the location might not be correct and you could set up a stationary one in error. Perhaps I should make it 5 times the home zone radius instead. Your thoughts?

**Comment by bryeartem** [comment]
That would maybe make more sense as people who know they have gps issues usually have already increased their zone size usually, no?  My home zone is only 100m.  But for I know we don’t drift much while here.

**Comment by gcobb321** [comment]
In the next release, the device is put into a stationary zone if it hasn't moved more than .05km in 10 minutes. Also the zone radius is 2 times the home zone radius and you must be more than 2.5 times the home zone radius (vs 3 Miles) to set one up. Additionally, when you are in a zone based on gps coordinates, the GPS coordinates are reset t I  The center of the zone.

**Comment by gcobb321** [comment]
Thought you'd like to know...

v1.0 of iCloud3 is now available for download

Go here  <https://github.com/gcobb321/icloud3>to download the latest 
version of iCloud3 and to review the documentation on the github.

A full list of changes enhancements since 0.86 are described in the 
ChangeLog.The Readme describes the functions and features of iCloud3 and 
contains many examples on how it provides a complete presence detection 
solution for Home Assistant.

Good luck. Let me know if you run into problems.

Gary



------ Original Message ------
