### ISSUE TITLE
There are no instructions for installing the Event Log

### ISSUE THREAD

**Issue by HVR88** [gcobb321/icloud3#204]
In the section titled "Installing the Event Log" there are no installation instructions.

https://gcobb321.github.io/icloud3/#/chapters/1.5-installing-icloud3?id=installing-the-event-log

The total of all the installation text summarizes to "Install iCloud3 repository from HACS" - the rest seems to be configuration information which is not useful until iCloud3 has already been installed and is accessible.

**Comment by gcobb321** [comment]
When iCloud3 starts, it checks the 'www\custom_cards' directory. If it doesn't exist, it is created. Then it checks the version of the 'icloud3-event-log-card.js' in the `custom_components\iCloud3` directory created by HACS. It the file in the `www\custom_cards` directory doesn't exist or is older than the one in the iCloud3 directory, the file is copied from the iCloud3 directory to the `www\custom_cards` directory.

**Comment by HVR88** [comment]
Sounds good for the missing files, but in the time I went over the install instructions I also didn't see any mention of how to start iCloud3.  So far it's unlike other HACS integrations I've installed, all of which required the installation of an integration via HA's own Integrations manager after installing their repositories via HACS.

If there's no need to install the files mentioned above, that would be best mentioned in the instructions. Right now it really looks like there's text missing because the section is titled "Installing the Event Log" and doesn't mention actual installation, just where the files are supposed to live once installed.

Also here: https://gcobb321.github.io/icloud3/#/chapters/1.5-installing-icloud3  it says in Step 4 "Install the iCloud3 Event Log card using the procedures below" - but below there are no procedures for this - only instructions for setting up Lovelace resource allocation for a file that doesn't exist and is supposed to be copied by starting iCloud3 - and no info on how to start it to get the files installed.

**Comment by HVR88** [comment]
Looks like this other page on the "dev" repo, does include instructions: https://github.com/gcobb321/icloud3_dev/blob/master/docs/chapters/1-installation.md#installing-the-icloud3-event-log-custom-card

But the page I linked in the opening post of this issue, which I thought were the official/only instructions, doesn't contain the same info.

**Comment by gcobb321** [comment]
iCloud3 is not yet installed as an integration. I’ve been working on a complete rewrite of iCloud3 for a while to support this, plus a lot of other things, and hope to have it done this summer. In the mean time, it is configured and it’s started using the configuration.yaml file. You have been through the iCloud3 docs. The step-by-step guide is in the docs[ here](https://gcobb321.github.io/icloud3/#/chapters/1.1-quick-start-guide).

**Comment by peecee69** [comment]
From all the documentation I've read, this looks like an awesome integration.  Thank you for writing this Gary!  A friend of mine showed me this component today and I'm looking forward to getting it installed. 

Having said that, since this doesn't show up under HACS and adding custom repositories (within HACS it's greyed out) are broken, it might be helpful to populate the manual install steps.  Currently, only the HACS method is covered in the docs.

**Comment by gcobb321** [comment]
iCloud3 is listed in HACS as an integration even though it is configured using a configuration file instead of being configured on the HA > Configuration > Devices and Integrations screen.

1. Go to HACS
2. Select Integration
3. Search for iCloud3
4. Select install. This will download the iCloud3 program, create the config/custom_configuration/icloud3 directory and copy the files to It.
5. Restart Home Assistant

You then have to manually update the configuration.yaml file to add the statements described in the iCloud3 docs to configure and start iCloud3.

I just checked HACS and it is showing v2.4.7 as the latest release available.

————————
Gary Cobb

**Comment by peecee69** [comment]
Gary,

Thank you for that info!  For some reason, icloud3 wasn't showing up in HACS when searching last night.  This morning it does.  I removed my (lame) manual attempt, installed via HACS, and it looked like it installed correctly.  Now off to configuration.  

Thank you again for writing this!  If you need help testing new features, count me in!

Paul
