### ISSUE TITLE
As per your request, Gary!

### ISSUE THREAD

**Issue by 26tajeen** [gcobb321/icloud3#209]
Hi Gary

As per your suggestion I'm submitting an issue here along with an event log.

Looking at the events in the GUI, I can clearly see my phone changed location at 8:36:52 AM, but looking at the event log I've emailed to you, I can see no such 'movement'.

I'm wondering if my sensors are setup wrong so that when icloud3 isn't "in control" like maybe polling is paused, the iphone app takes over - and as we all know the iphone app is rubbish at accurate locations which is why we use icloud3!

many thanks

**Comment by gcobb321** [comment]
I looked at the log yesterday but now, gmail seems to have lost it. However, when your look at the Select Zone statement in the Log for when you exited Home and went into the other zone, it shows the the distance from each zone, the radius of the zone and the gps accuracy of the current location.  you have a 50m Home zone, another zone that is real close to the Home zone with a 150m radius and the device Location has a GPS accuracy of 96m. The accuracy is the /96m after the latitude/longitude position. If the 96m accuracy is greater than your gps_accuracy_threshold parameter, that would be through away when you go to a not_home state. But because the other zone is so close to Home, it didn’t go to a not_home state, it went into that zone instead. The gps accuracy is like a +/- of the latitude/longitude position where you are somewhere inside a circle with a radius of 96m from that position.

**Comment by gcobb321** [comment]
This is the log. I didn’t associate DC Ebon with lancelon in the emails. Also, the iOS app moved you into Preston’s zone instead of away because the zones are so close together. You might want to reduce Preston’s size from 150m to 100m. 

Log file info redacted

**Comment by 26tajeen** [comment]
Thanks, Gary, weirdly, the zone you call Preston's is definitely set to 50m in the Home Assistant config. Unless there's somewhere else it could be set to 150m, I'm confused. I've looked at it on the map the GUI offers and it shows both circles as being the same size. 
![map](https://user-images.githubusercontent.com/28266789/161027516-69ec9b9c-f72f-4923-b3ce-4a7f72866b1a.PNG)


Btw, is it possible for you to remove the name of the zone from this ticket? Or redact the log completely so my lat/lons and zone names are not visible/identifiable? MANY THANKS!!

**Comment by 26tajeen** [comment]
@gcobb321 any chance of anonymising that log please Gary

**Comment by gcobb321** [comment]
Done. At one time, the iOS app used a 100m default radius for a zone and would use that regardless of the zone size. That was messing up iCloud3 because the app would put the phone into a zone when it really wasn’t and then iCloud3 would take it out and things would go downhill from there. I’ll look and see if iCloud3 it’s still doing that and, if it is, send you a special version without it to see if that works. 

It all starts with gots accuracy. AS I recall,  When iCloud3 gets an exit Zone trigger, it will throw it away if the distance is within twice (maybe 1.5) times the Home zone size. It might have got caught up in that code too and the combination of things put it into the other zone.

**Comment by 26tajeen** [comment]
Hi Gary,
email sent! :-)
with a pic
best wishes
D

**Comment by gcobb321** [comment]
It’s all related to close zones and the iOS app exiting zones because of a poor gods accuracy. And iCloud3 trying to react to poor data.
