### ISSUE TITLE
Constant updates when next update time is on the next day

### ISSUE THREAD

**Issue by mikes02** [gcobb321/icloud3#21]
I believe I have found the reason why this is occurring.  It will happen up until midnight when the next update time is for the next day.  The current logic is using seconds and not a timestamp to determine if an update is needed.  So if the next update is at 12:01am the next update seconds will be 60 seconds since it is only 1 minute into the next day.  However the current update seconds will be closer to 86400.  The logic will trigger an immediate request to the device if the current update seconds is greater than the next update seconds.

Here is the current if statement on the prerelease icloud3.py line #911
`  elif (self.this_update_seconds >=
                            self.next_update_seconds.get(devicename)):
                    device_needs_updating_flag = True`

Line #1490 shows the next update seconds being set based the time being for the next day
` #check if next update is past midnight (next day), if so, adjust it
        next_poll = self.this_update_seconds + interval
        if next_poll >= 86400:
            next_poll -= 86400
            self.poll_count_yesterday[devicename] = self.poll_count[devicename]
            self.poll_count[devicename] = 1`

I added some logging just to make sure that is correct on the elif on #911
`                    log_msg = ("DEVICE NEEDS UPDATE* {}, "
                         "From={}, To={}").format(devicename,
                         self.this_update_seconds, self.next_update_seconds.get(devicename)) 
                    self._LOGGER_info_msg(log_msg)`

![image](https://user-images.githubusercontent.com/47875101/53214377-f38da100-3611-11e9-9745-fa5002cccb9d.png)

**Comment by gcobb321** [comment]
Thanks for the heads-up. I found this bug and have fixed it in the next update.

**Comment by gcobb321** [comment]
Thought you'd like to know...

v1.0 of iCloud3 is now available for download

Go here  <https://github.com/gcobb321/icloud3>to download the latest 
version of iCloud3 and to review the documentation on the github.

A full list of changes enhancements since 0.86 are described in the 
ChangeLog.The Readme describes the functions and features of iCloud3 and 
contains many examples on how it provides a complete presence detection 
solution for Home Assistant.

Good luck. Let me know if you run into problems.

Gary



------ Original Message ------
