### ISSUE TITLE
Request:  Set initial stationary zones to Home coordinates

### ISSUE THREAD

**Issue by manonstreet** [gcobb321/icloud3#22]
It appears that when iCloud3 starts up and creates stationary zones, it sets the coordinates as follows:
`Stationary Zone Set > maximus_stationary, GPS-(90, 180)']`

This location is in the Arctic Ocean.  The coordinates then get overwritten when an actual temporary stationary location is detected.

This has not been an issue thus far; however in the newest release of HA (.105 beta), there is now a visual zone editor for managing zones.  If HA starts up and tracked devices are located in a zone, the stationary zone won't update and those coordinates values (90, 180) will be reported.  When entering the visual zone editor, the map is zoomed way out in order to show all zones centered on the screen. This is not a bug per se, but a little annoying.

If initial values of the stationary zone coordinates were set to Home, the current location of tracked devices, etc.. it would allow the map to center around all relevant zones for easier editing.

**Comment by gcobb321** [comment]
At one time, the initial value of the stationary zone was the Home zone. It created problems with the iOS App since it would locate the device in both zones and the device_tracker state value was inconsistent. When the current zone is determined, the distance from the device to the zone is taken into consideration. The zone with the smaller distance wins. If the Home zone is used as the stationary zone location, when you approach Home, the iOS App will issue zone an enter triggerfor the stationary zone since it has a bigger radius than the Home zone, then it will issue an enter  trigger for the Home zone. The same will be true when you leave Home. So setting it to the Home zone will not work. 

Things to check out:
1. The stationary zone has an icon. I wonder if it is displayed on the map only because of the icon and if there is no icon, it will not be displayed. 
2. Setting the stationary_zone to someplace close to the Home zone.

I'll look at it more closely when I update to .105.

**Comment by manonstreet** [comment]
Regarding #2, another approach could be expose configuration options for the coordinates for the initial stationary values as an override the default values.

**Comment by gcobb321** [comment]
iCloud3 v2.0.6 addresses this issue. See the change.log for more into.

I just updated the iCloud3 v2.0.6 release candidate in the 'development v2.0.6' directory in the iCloud3 GitHub repository [here](https://github.com/gcobb321/icloud3/tree/master/development%20v2.0.6) . Download the 'device_tracker.py' and 'pyicloud3_ic3.py' files and copy them to the 'custom_components/icloud3' directory.

**Comment by manonstreet** [comment]
Works great.  Thanks Gary!
