### ISSUE TITLE
Various issues to be reviewed/fixed.

### ISSUE THREAD

**Issue by codepoet4** [gcobb321/icloud3#22]
Sorry for not individualizing each issue, I didn't have time to break them out.  I've attached my version of your icloud3.py with fixes that seem to filter out a lot of problems for me.  You probably would make the 'fixes' in a different way, so I'll leave that decision up to you.  

The file is commented - just search for 'CP' - these are all my comments with explanations.  

Hopefully this helps.  

[icloud3_cp.txt](https://github.com/gcobb321/icloud3/files/2897435/icloud3_cp.txt)

**Comment by gcobb321** [comment]
I've looked at each of the items and all are addressed in the next release. I had already fixed most of them but others gave me some ideas on enhancements.. Thanks.

**Comment by gcobb321** [comment]
Thought you'd like to know...

v1.0 of iCloud3 is now available for download

Go here  <https://github.com/gcobb321/icloud3>to download the latest 
version of iCloud3 and to review the documentation on the github.

A full list of changes enhancements since 0.86 are described in the 
ChangeLog.The Readme describes the functions and features of iCloud3 and 
contains many examples on how it provides a complete presence detection 
solution for Home Assistant.

Good luck. Let me know if you run into problems.

Gary



------ Original Message ------

**Comment by codepoet4** [comment]
Thanks!  I’ll give it a go!
