### ISSUE TITLE
Device name and quotes - entity matching

### ISSUE THREAD

**Issue by chrissearle** [gcobb321/icloud3#231]
v2.4.7

I feel like I may be missing something obvious here.

I have my phone, and three others have phones in the same apple family.

Two of them (mine and one other) are working fine. These have no apostrophe in the device name.

Two of them have a single quote/apostrophe in the name in the phone settings and are failing.

I get the following error - anonymised - we will use `Test's iPhone` for this example:

config_ic3.yaml:

```yaml
  - device_name: Test's iPhone
    name: TestName
```

Error in Stage 3 > Identify iOS App entities, Verify tracked devices:

```log
iCloud3 Error for TestName (test_s_iphone)/test_s_iphone > The iCloud Account for REDACTED did not return any device information for this device.
```

Yet - I can see the name via find my app on mac/iOS and I can _also_ see the name in:

Stage 2 > Set up tracked device parameters

```
test_s_iphone > Name-TestName, Type-, inZoneInterval-2 hrs
```

and Stage 2a > Authenticate iCloud Account, List Trackable Devices:

```log
tests_iphone > Test’s iPhone, iPhone
```

So - it seems like we're getting thru stage 2 but failing in stage 3.

**Comment by gcobb321** [comment]
The device name goes thru some conversion routines in HA that create the device_tracker entity name and that has to match the iPhone name in Settings > General > About. Sometimes that might not match the conversion Apple does to store it in your iCloud account. This generates the error you see where the device name can not be found in the iCloud data.

The best practice, in my experience is to put the entity name the iCloud account creates as the device_name parameter instead of the friendly name. And do not use the 's in the name. My devices are gary_iphone,, gary_ipad, lillian_watch,, etc.

**Comment by chrissearle** [comment]
Thanks. It turned out that all I needed to do was to remove the ' in the config_ic3 file - since the apple name conversion was stripping it. All four devices are now connected.
