### ISSUE TITLE
dynamic polling now working as described

### ISSUE THREAD

**Issue by jebeke65** [gcobb321/icloud3#24]
I have IOS App settings set as described (zone enter/exit, background fetch and significant location enabled). I even get Home assistant notifications on my iPhone for each zone I defined.
Nevertheless, when today i left my work zone, it only got triggered way too late on my way home.
Are there things I can check for this wrong behaviour ?

**Comment by gcobb321** [comment]
This is usually from sleeping phones or the HA app not picking up a zone exit. Bad reception and GPS errors often drive me nuts. Not much you can do about gps errors and old location issues.

**Comment by gcobb321** [comment]
Thought you'd like to know...

v1.0 of iCloud3 is now available for download

Go here  <https://github.com/gcobb321/icloud3>to download the latest 
version of iCloud3 and to review the documentation on the github.

A full list of changes enhancements since 0.86 are described in the 
ChangeLog.The Readme describes the functions and features of iCloud3 and 
contains many examples on how it provides a complete presence detection 
solution for Home Assistant.

Good luck. Let me know if you run into problems.

Gary



------ Original Message ------
