### ISSUE TITLE
Error: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by RobertDWhite** [gcobb321/icloud3#24]
Hello,

I just wanted to post this error I am getting all the sudden. Near the end of 2019, I had this plugin working flawlessly with fmf. Recently, I have not had success where it all the sudden says "no devices to track". No emails changed on my AppleID, so I just found that weird.
However, a **new** error is the first about 'NoneType' object. 

```raise PlatformNotReady
homeassistant.exceptions.PlatformNotReady
2020-02-19 13:16:59 ERROR (SyncWorker_9) [custom_components.icloud3.device_tracker] 'NoneType' object is not iterable

Traceback (most recent call last):
File "/config/custom_components/icloud3/device_tracker.py", line 5645, in _setup_tracked_devices_for_fmf
for contact in fmf.contacts:
TypeError: 'NoneType' object is not iterable
2020-02-19 13:16:59 ERROR (SyncWorker_9) [custom_components.icloud3.device_tracker] iCloud3 Error: Setup aborted for Group-group1, Username-**************. No devices to track.```

**Comment by gcobb321** [comment]
I had a user in the UK that also had this problem a few week ago. As it turns out, Apple is sometimes not returning Contact info for devices being followed in the non-2fa account. However, it is returning 'Following' data which has the info needed (except the first name) to identify the devices being tracked.

I just updated the iCloud3 v2.0.6 release candidate in the 'development v2.0.6' directory in the iCloud3 GitHub repository [here](https://github.com/gcobb321/icloud3/tree/master/development%20v2.0.6) . Download the 'device_tracker.py' and 'pyicloud3_ic3.py' files and copy them to the 'custom_components/icloud3' directory. Then restart HA and see if your devices are now tracked.

Be sure to see the note in the Change.log about the track_devices parameter as it relates to the First Name.

**Comment by RobertDWhite** [comment]
Hi @gcobb321 
Thanks for your incredibly quick response. I probably mucked something else up, as I am receiving the same error. 
Thank you!

**Comment by gcobb321** [comment]
1. I'd sign  back into the non-2fa account and make sure everything is still set up. Check that the contacts can still be seen in the FindMe app. See iCloud3 documentation[ here](https://gcobb321.github.io/icloud3/#/chapters/1-setting-up-icloud-account?id=find-my-friends-fmf-tracking-method) . Also make sure the devices 2fa accounts show as followed.
2. If everything looks ok, Put the 'log_level: debug+rawdata' parameter in the iCloud3 config and see if the contacts email records are being returned from Apple Web Services in The log file.
3. You might then want to turn on the debug logging for pyicloud_ic3.py described in the change.log documentation. 
4. I may need to then see the HA log file. You could email it to geekstergary@gmail.com and I'll see if I shoot anything.

**Comment by RobertDWhite** [comment]
SO. I eventually gave up since I assumed it had to do with my setup somehow (recently switched to unraid from synology, and had some other server changes). I went ahead and tried to reinstall the old HA iCloud integration, which worked, and asked for a code sent via text. After entering it, I went BACK to iCloud3 plugin, and all works perfectly now... I am using the v2.0.6rc files you mentioned.

**Comment by gcobb321** [comment]
Reopen the issue if it still exists in v2.1

**Comment by RobertDWhite** [comment]
The issue resolved. Just for your info too, I have 2FA turned on, and if I completely remove iCloud3 as well as the auth from the HA iCloud integration, then start ove with the following steps, 2FA accounts work with no popups incessantly: 1) add HA iCloud integration, follow steps to authenticate with mobile 2FA device, 2) comment out the iCloud integration on config.yaml, 3) enable iCloud3 integration. 2FA is working with iCloud3, with not incessant popups (only pops up once when HA restarts). The 'NoneType' error is resolved. Nice work!
