### ISSUE TITLE
Travel Time Minutes Sensor Name?

### ISSUE THREAD

**Issue by broyuken** [gcobb321/icloud3#241]
Quick question, I've started removing some of the sensors from ic3 and others to try to keep my database size down, and can't figure out how to keep the one you added in https://github.com/gcobb321/icloud3/issues/159. I looked at the table from https://gcobb321.github.io/icloud3/#/chapters/2.4-sensors and have added this as my device tracker,
```
platform: icloud3
username: !secret icloud3_username
password: !secret icloud3_password
create_sensors: ttim
```
 but it only gives me the sensor.broyuken_iphone_travel_time entity, not the sensor.broyuken_iphone_travel_time_min sensor that I had before. what is the code for this new sensor?

**Comment by gcobb321** [comment]
Hey. It probably doesn't have a code or it is combined with the ttim. In any case, it really won't matter since I hope to put up a beta of v3 in a few days. Everything will change and those codes will go away to be replaced by check-boxes in the on-line Integerations Configurator. For an idea of what is going on, take a look[ here](https://gcobb321.github.io/icloud3_v3_docs/#/)

**Comment by gcobb321** [comment]
Try ‘mtim’ for the travel_time_min sensor. I found it reviewing the migration code.

**Comment by broyuken** [comment]
Just following up on this, is v3 being released soon?

**Comment by gcobb321** [comment]
I'm going to put it up tomorrow morning (Sat, 12/17). It will be on the gcobb321/icloud3_v3 repository. I'll let you know when it is available.

**Comment by gcobb321** [comment]
**iCloud3 v3.0.0 beta 1 is available**
OK guys. Here it is. Have fun and be kind. 

iCloud3 v3.0.0 beta 1 has been uploaded to the iCloud3_v3 repository. It can be found on the [v3 Releases page here](https://github.com/gcobb321/icloud3_v3/releases/tag/v3.0.0-beta.1).
