### ISSUE TITLE
Custom Component Error.. FYI

### ISSUE THREAD

**Issue by cryogenx** [gcobb321/icloud3#26]
Seeing this on my HA instance, FYI

![screen shot 2019-03-07 at 11 38 31 am](https://user-images.githubusercontent.com/731595/53972874-a3ace080-40cd-11e9-8a84-9243737d5260.png)

**Comment by gcobb321** [comment]
The guys at HA are changing things around for all custom components and the directories they are using. There are detailed discussions on this in the HA release documentation. Read about it [here](https://developers.home-assistant.io/blog/2019/02/19/the-great-migration.html).

Instead of 'custom compoents/device_tracker' directory that contains 'icloud3.py', you will have to use 'custom components/icloud3'  directory that contains 'device_tracker.py'.

**Comment by cryogenx** [comment]
interesting read, sorry im playing catch up only been on HA for about a week.

**Comment by humphrep** [comment]
I tried using the new custom_components.json file and received the following error in my log:
simplejson.errors.JSONDecodeError: Invalid control character '\n' at: line 2 column 16 (char 17)

So I forked off from the main and rebuilt the file, and now the custom updater is working when pointing to my forked version of the file.

I am not a developer, so I don't know how to request this to merge into the main, but you could go to my fork, and grab the raw version of that file and copy it into yours.
