### ISSUE TITLE
yaml Zones are not being loaded when iCloud3 starts

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3#283]
HA was not passing the yaml zones into iCloud3 when starting up. iCloud3 was only loading zones configured using _Settings > Areas & Zones_ The zip file below fixes this problem.

Unzip the attached start_ic3.zip file into the _icloud3/support_ directory and restart HA. 

[start_ic3.zip](https://github.com/gcobb321/icloud3/files/12908040/start_ic3.zip)

**Comment by poudenes** [comment]
Done, now I see all the zones in Stage 2 in the list.

**Comment by poudenes** [comment]
It seems this issue is back again.

v3.0.rc8

<img width="458" alt="Screenshot 2023-11-07 at 18 30 32" src="https://github.com/gcobb321/icloud3/assets/4399532/c5fa6c02-734a-4992-b758-ffc73ef28c0f">

https://community.home-assistant.io/t/icloud3-v3-idevice-tracker-version-3-prerelease-version-is-now-available/267554/960?u=poudenes

**Comment by gcobb321** [comment]
Actually there was a bug that was terminating the zone setup process when iCloud3 was restarted and a stationary zone existed. This HACS been fixed in rc9. The zones are loaded correctly on an HA start and when the stationary zone does not exist.

**Comment by poudenes** [comment]
Tried to update iCloud3 in HACS. I don't see rc9. Refreshed and also restart HA. But no rc9 to install.
3.0.rc8 is latest one in the list.

**Comment by gcobb321** [comment]
@poudenes 
I have not released rc9 yet and will probably do that next week.
