### ISSUE TITLE
All HACS files gives 404 after installing

### ISSUE THREAD

**Issue by johhiq** [gcobb321/icloud3#290]
I've installed iCloud3 v3b8 and after that all my other HACS-cards stopped working. Clicking on "Open Source" in Hacs just gives 404. I've tried several tips and trix including removing, and reinstall. I gave up and removed iCloud a couple of weeks ago to install everything else once again. Leaving iCloud3. But after every thing working well again I gave it an other try. Every thing worked well at first but after a while the problems is back. "Custom-elements doesn't exist" for all custom cards in HACS. AND I also get "Unhealthy system - Not privileged" which seams strange. In notifications I get "The Event Log Custom Card was added to the Lovelace Resource list. File-icloud3-event-log-card.js ". This is not the case. There is no card in the resource list. And yes! I have cleared cach. 
I'm out of ideas of what to do. Running HASSIO in Docker on a Debian 12. 
Any Idea? What have I missed? Sensor e.g. do work.

**Comment by gcobb321** [comment]
The only experience I have with Docker is setting up an HA development environment on my Windows computer. Although it kinda worked, I did have some issues.
1.  iCloud3 was not able to get data from the iOS app so that would not work. I think that was an HA issue since everything was ok on my RPi
2. There were some directory name problems. Docker was adding a ‘workspace…’ prefix to the directory names.  I had to consider this when checking _Event Log_ and other names. I suspect this was a VSCode-to-Docker-to-HA serious issue. Not really a problem but something I had to work with. 
3. The one that really got in the way and, at times, made it unusable was the problem communicating with the iCloud account and the Apple Web Servers. When starting up, it might take 2-4 minutes to get data back from Apple. Especially when authenticating iCloud account access. It would return errors and time out. The Python  module that does this was developed years ago and is not really maintained. It is single thread and does not support async i/o. Which means it can hang HA at times since it just sits there and waits for the data to be returned after a request instead of requesting it, giving control back to HA and then c continuing once it is reduced. I suspect that it’s caused by a lot of things. 

I’m running on a RPi with a straight install. No docker. Be Debian. I think you have an environment e with a lot of parts I know nothing about t that all have to interact with each other and iCloud3 probably will not work, mainly due to # 3 above.

**Comment by johhiq** [comment]
Thank you for your quick reply. Fingers crossed - I think it's working now. The integration it self seems to work, the sensors eg. show what to expect, and in the log files everything looks ok. But the other installed custom cards stopped working and I was constantly notified about refresh and info about event log card. Probably my bad, I use storage mode. To get it working I added the ref in config (url: '/local/icloud3/icloud3-event-log-card.js') manually, updated all info in Hacs (and/or) downloaded every custom lovelace again and now it works. At least what I can tell. I will keep an eye on unwanted behavior mentioned in no3, hopefully it's stable.
