### ISSUE TITLE
iCloud3 V3 no photo on device tracker

### ISSUE THREAD

**Issue by sandernaus** [gcobb321/icloud3#294]
For a device added through friends and family sharing, I've set a photo. However, this photo appears only for the`sensor.<device>_badge` and not for the `device_tracker.<device>`.

Where, for my device, the photo is set for both the sensor and the device_tracker. Is this a known bug?

For the device with the issue, I also see the following error in the logging. Not sure if that's related.
```
INTERNAL ERROR >; iCloud Update

File... > `/device_tracker.py`

• Line.. > 618, in write_ha_device_tracker_state(...)

• Code > self.async_write_ha_state()

• File... > `/usr/src/homeassistant/homeassistant/helpers/entity.py`

• Line.. > 720, in async_write_ha_state(...)

• Code > raise RuntimeError(f`Attribute hass is None for {self}`)

• Error. > RuntimeError: Attribute hass is None for <DeviceTracker: <DEVICE>/iphone>
```

**Comment by gcobb321** [comment]
1. iCloud3 version? The latest is rc8. 
2. Do you have other devices that show the picture on both the sensor badge and device tracker entities correctly?
3. If # 2 is yes, what happens if you try changing the picture to the same one that shows correctly?
4. Are there any other errors related to iCloud3? HASettings > System > Logs

 I would be interested in a log file. Do _Event Log > Actions > Turn on Debug Logging_   Then _Event Log > Actions > Restart iCloud3_. Let it run until you get the error and send iCloud-0.log to geekstergary@gmail.com and I’ll see if I can see what is causing it. Somehow that Device May not be getting completely set up because ‘hass is None’ error

**Comment by sandernaus** [comment]
After reviewing my configuration again, I found some leftover files from the V2 version. This caused some old entities not to be cleaned up.

After cleaning everything, the pictures work as expected, and the errors disappeared in the logs.
