### ISSUE TITLE
More of a question

### ISSUE THREAD

**Issue by thenoid** [gcobb321/icloud3#312]
Maybe I missed it in the documentation/setup, my apologies if that is the case.  I'm trying to figure out some weird tracking issues.

When using icloudv3 - should the icloudv3 tracking entity be the only one associated with a user?

EG:  I setup `$myIphone` with the HA app and in icloud3 (with the app associated) - but then under my "people" profile I have the icloudv3 entity and the app entity?  

![image](https://github.com/gcobb321/icloud3/assets/2242308/17ded683-d1ba-43df-9c69-1650ce0027ca)
![image](https://github.com/gcobb321/icloud3/assets/2242308/440c46d2-90f0-456a-837e-cc66f5ad0e9c)

**Comment by gcobb321** [comment]
The HA person entity should be the iCloud3 device tracker entity only. It should not include the Mobile App device tracker entity since iCloud3 monitors it and uses it as a data source. iCloud3 also prevents phantom Zone exits caused by gps wandering problems and looks at the gps accuracy before updating a devices location.
