### ISSUE TITLE
User devices keep changing id

### ISSUE THREAD

**Issue by JooRuu** [gcobb321/icloud3#320]
I have 3 devices set up. Randomly 2 of those devices seem to get mixed so that the devices assigned to the user id gets changed. Some times 1 device gets assigned to 2 users which causes them to stop updating. 
is there a way to fix this problem?

**Comment by gcobb321** [comment]
What version of iCloud3 are you running?
What are the device names?

**Comment by JooRuu** [comment]
Release Candidate - v3.0.rc10.4 (2/18/2024)

**Comment by gcobb321** [comment]
When iC3 starts, it gets the device info from Apple. This includes the phone name from the Settings App > General > About/Name (?). It also gets the Apple Device's internal  id that is a string of numbers /letters about 30-chars long. It is that ID that Apple uses to references the device. During startup, iC3 matches up the phones name with the data returned and if the id is different, it updates the config files with the new id. It tries to see if there are devices with similar names because most people do not change the devices name when it is sold/replaced/returned to Apple to use the new name. The new name is sometimes the Old name, the Old (2) name or something like it.  

Look for something like that in the Event Log > Stage 3, 4, 5 to see if there are any devices that are alike. Also check the Update Devices config screen for them and see if the model numbers are the same or different.

**Comment by JooRuu** [comment]
We updated the names on the phones. That  fixed the problem.
Thank you for the rapid and professional response!
