### ISSUE TITLE
Unable to customize sensor attributes

### ISSUE THREAD

**Issue by andystewart999** [gcobb321/icloud3#34]
Hi - I'm using the '_zone_name1' in my automations as recommended, but to make my life a little bit easier I've tried editing two attributes via the customize feature:
 .entity_picture
 .friendly_name

Neither of them have 'taken' for some reason, all it has is state, icon and the default friendly_name.  Is there something special about the sensor objects you create?

Cheers,
Andy

**Comment by gcobb321** [comment]
ICloud3 creates the sensors when it loads so they are not part of the of the usual sensors defined in HA. Because of this, you are not able to customize them like you want to. The only way to do that would be to create a template sensor that mirrors the iCloud3 sensor’s state and then use the template sensor on your automations and scripts.

**Comment by andystewart999** [comment]
That makes sense - thanks Gary, I'll create a template sensor as you describe.

Cheers,
Andy

**Comment by gcobb321** [comment]
Release Candidate 4 is now available. See the Release Candidate Change Log file for information on the changes. Download it [here](https://github.com/gcobb321/icloud3/tree/master/development%20v2.2.0-rc4)

**Comment by andystewart999** [comment]
Thanks as always for your continued work on this Gary.  

I've got two questions straight away:
1 - which is the theoretical 'best' location method - Family Sharing (with 2fa) or Find my Friends (via a 3rd party, non-2fa account)?  I've got the latter set up and I'm happy to stay with it, but if there are efficiency advantages reverting back to Family Sharing then I'll do so.

2 - I've got the Stationary Zone about 500m from my house (the default position) but it's never mode position in the last month or so that I've been using the latest release.  I know from the doco that it's supposed to update automatically, but it seems to have been there for ages now.  How can I clear it out and/or force an update?

Thanks again,
Andy

**Comment by gcobb321** [comment]
I am using famshr right now and it's hard to tell which is better from a performance point of view done I haven't been traveling to much. The event log now shows better stats every 3 hours (authentications, web Svc calls, etc).  If you are out running around, look at the calls vs the discards because of old data and see what works better for you.

I've moved the initial stationary zone from.5km to 1km from the Home zone. Let me know if this isn't enough and I can easily add a parameter to let you move it further away.
