### ISSUE TITLE
GPS Radius Overlap Not in Zone

### ISSUE THREAD

**Issue by DaAwesomeP** [gcobb321/icloud3#348]
Hello!

Thank you for providing an amazing component! I have noticed an issue where if a device is at the edge of a zone such that the GPS accuracy radius overlaps with the zone (but the center point of the device is not in the zone), then the device will not be recognized as in the zone. This results in a lot of zone in/out back and forth particularly for indoor locations where the device will appear to move around quite a bit. This is a different behavior than the mobile app which seems to account for the GPS accuracy radius when determining if a device is in a zone.

Thanks!

**Comment by gcobb321** [comment]
The mobile app, as far as I know, puts a device in a zone when it is within 100m of the edge of the zone and does not look at the accuracy. It will also move a device out of the zone if it is further away from its center than the radius. iCloud3 acts differently. It will move a device into a zone if its distance is within the radius or if the mobile app/HA has triggered a zone enter. It will not move it out when the accuracy is poor but waits until the distance is greater than 2-times the radius. 

Zone edges are hard to deal with due to the accuracy, mobile app Zone changes and tries to avoid f false exits due to gps wandering
