### ISSUE TITLE
No history for devices on map view

### ISSUE THREAD

**Issue by pdawg17** [gcobb321/icloud3#350]
I am on HA 2024.7.0 and don't have history anymore. The current locations update. I have had this working well for quite a long time so no changes on my end.

**Comment by gcobb321** [comment]
It’s all on the HA end. They did something that is causing a lot of errors in the recorder routine. I am in Switzerland and cannot do an update to iCloud3 but have changed since code to bypass the errors. Try the instructions below. I’ll look at it when I get home. 

I am in Switzerland and cannot release an update to iCloud3 to fix this error. However, I have updated the code in GitHub.
1. Download the support/recorder_prefilter.py file in the iCloud3 GitHub repository [here](https://github.com/gcobb321/icloud3_v3/blob/main/custom_components/icloud3/support/recorder_prefilter.py) and save it to the icloud3/support directory. (Look for ‘Raw’ in the menu bar above the code on the right. The Download icon is the 2nd icon to the right)
2. Restart HA

**Comment by smithbill17** [comment]
So since updating to 2024.7.0, all my History Graphs were 'flat lining' (see attached image for an example).

Looking at the logs, it started to become apparent that there was some kind of start up issue with the iCloudv3 integration which I had only recently installed, and this seemed to be causing an issue with recording data. So that brought me here.

So I have downloaded & installed your suggested support/recorder_prefilter.py and simultaneously the HA developers have release a new update v2024.7.1 with various updates (not sure if any of them are relevant to this issue).

Anyway, a combination of your replacement recorder_prefilter.py & the v2024.7.1 update, seems to have fixed the error & my History Graphs are once again updating.

I'll continue to monitor them & see if the issue is resolved 
![image](https://github.com/gcobb321/icloud3/assets/66825587/2ebd3446-afcf-45b5-9552-931d795a221d)

**Comment by pdawg17** [comment]
> So since updating to 2024.7.0, all my History Graphs were 'flat lining' (see attached image for an example).
> 
> Looking at the logs, it started to become apparent that there was some kind of start up issue with the iCloudv3 integration which I had only recently installed, and this seemed to be causing an issue with recording data. So that brought me here.
> 
> So I have downloaded & installed your suggested support/recorder_prefilter.py and simultaneously the HA developers have release a new update v2024.7.1 with various updates (not sure if any of them are relevant to this issue).
> 
> Anyway, a combination of your replacement recorder_prefilter.py & the v2024.7.1 update, seems to have fixed the error & my History Graphs are once again updating.
> 
> I'll continue to monitor them & see if the issue is resolved ![image](https://private-user-images.githubusercontent.com/66825587/346179507-2ebd3446-afcf-45b5-9552-931d795a221d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMDEyNTMsIm5iZiI6MTcyMDIwMDk1MywicGF0aCI6Ii82NjgyNTU4Ny8zNDYxNzk1MDctMmViZDM0NDYtYWZjZi00NWI1LTk1NTItOTMxZDc5NWEyMjFkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDE3MzU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMjZkZmIwMjRiYjhmMWY5NTExMjhmOWRmNTRlZWNhNmU3YzczOTM0ZTQ5NmY5YTg4ZDliMDQ4NThjNWU0MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6xp2lVF-UniT0VmyGhNOYHtMgCQ2ELTX2rHcfYH6lI0)

Can you direct me to how to place the file in HA? (full location of folder/what to use to replace the file) It doesn't appear that 2024.7.1 fixes it...

**Comment by smithbill17** [comment]
> 
> Can you direct me to how to place the file in HA? (full location of folder/what to use to replace the file) It doesn't appear that 2024.7.1 fixes it...

I used the 'File editor' AddOn, browsed to the  custom_components/icloud3/support folder, renamed the existing recorder_prefilter.py file & then uploaded the new recorder_prefilter.py file and finally restarted Home Assistant.

**Comment by gcobb321** [comment]
@smithbill17 
Thanks for explaining the install. I’m currently in Switzerland and will get an update out when I get home mid-July

**Comment by gcobb321** [comment]
Completed with iCloud3 v3.0.5.5/v3.0.5.6
