### ISSUE TITLE
Support icloud3 config file for 2.2 to be outside of the custom_components directory

### ISSUE THREAD

**Issue by tmchow** [gcobb321/icloud3#41]
Currently with 2.2.0rc5, the support for the separate config file is great. One issue is this:

>  The new configuration file, config_ic3.yaml in the iCloud3 custom_component directory, lets you can specify most of the configuration parameters normally found in the HA configuration file

It's probably better that this file is outside the `custom_components` folder so those of us using git or other code versioning can more easily manage the config file changes since all those files in that folder are managed by HACS.

Perhaps the config value `config_ic3_file_name` should take a path instead?

**Comment by gcobb321** [comment]
1. The ‘config_ic3.yaml’ is not distributed by hacs so it shouldn’t be controlling/monitoring it as farAs I know. The one distributed is ‘config_ic3_sample.yaml’. That way, I can send out an updated sample file with a new release.
2. The ‘config_ic3.yaml’ is the default name. It can be changed by the ‘config_ic3_file_name’ parameter. But it is still stored in the custom components directory. I could add a check for a ‘/‘ in the file name to let you store it in another directory. Would that work for git handling.

Coming up in rc6 is the ability to monitor the Event Log card version (icloud3-event-log-card.js) in the ‘www/custom_cards’ directory and automatically update it if there is a new version in the iCloud3 custom components directory. It will also create the directory on a new install if it doesn’t exist. A configuration parameter also lets you change the location if your cards are somewhere else. I did this since hacs can not install in a custom components and a Lovelace card directory on the same installation/update.

————————
Gary Cobb

**Comment by tmchow** [comment]
@gcobb321 regarding #1, yes I know that. I'm not suggesting HACS or icloud3 created that file. My point was the instructions tell us to create a file, and the instructions say to put it in the `custom_components` directory.  I think its better off in `/config/` instead and if it's less work, just change the file to be required in that location vs making it entirely configurable.  That would work for git handling.

**Comment by gcobb321** [comment]
Understand. I need to change the docs to make it clearer that it’s completely optional and anything in it overrides the HA configuration. My thinking was, since it is another way to configure iCloud3, and its only Associated with iCloud3 and the ha guys want to keep all files associated with a custom component in one directory, it belongs in the iCloud3 directory. Having it an optional parameter lets you Keep it where you want.

Thanks for the feedback and suggestions.

————————
Gary Cobb

**Comment by tmchow** [comment]
@gcobb321 one thing to consider is publishing the event log card in HACS separately as a  front end card. This way updates are all Handled by hacs

**Comment by gcobb321** [comment]
1. The Event Log is always updated with an iCloud3 release so publishing as a standalone hacs item doesn't apply. I checked to see if hacs could install both items in different locations in the same update and it can not.
2. Release Candidate  #6 checks the version number of the Event Log in the *custom_components/icloud3* directory with the one in the *www/custom_cards* directory and updates it if it is older. The configuration parameter, `event_log_card_directory`, lets you specify another directory if the Event Log is not in the *www/custom_cards* directory.
