### ISSUE TITLE
Devices not correctly detected, restart iCloud3 immediately fixes it

### ISSUE THREAD

**Issue by tmchow** [gcobb321/icloud3#42]
With 2.2.0rc5, when I restart HA (and iCloud3 is restarted), I will have errors in logs about device not being tracked but prior to restart they were correctly tracked.  If I restart iCloud3 (using the button on the iCloud3 entity log card), the devices always get picked up.

Error I see is:

```
iCloud3 Error for Wife (wife_iphone)/wife_iphone > The iCloud Account 
for me@me.com did not return any device information for 
this device when setting up Family Sharing.

 1. Restart iCloud3 on the Event_log screen or restart HA.
 2. Verify the devicename on the track_devices parameter if the error persists.
 3. Refresh the Event Log in your browser to refresh the list of devices.
```

Again, if I restart iCloud3 immediately, it's fixed.

**Comment by gcobb321** [comment]
I’ve seen this too but not all the time. Just every once in a while. I haven’t dug into it yet but think it’s a timing issue between the request for valid devices and ha setting up multiple threads and getting a response from iCloud web services.  I suppose I could add a check to retry getting the device info on startup and only give the error message if it fails on the retry.

————————
Gary Cobb

**Comment by gcobb321** [comment]
The iCloud3 Release Candidate has been updated and can be downloaded here. See the Change Log-Release Candidates a list of the items that were addressed in this Release Candidate.

The first item below is an important change that corrects the iOS App sensor monitoring function that generates the zone enter/exit and location change triggers which were not being detected after the iOS App and HA were updated.

The only programs that were updated are:

- device_tracker.py
- icloud3-event-log-card.js

------------------
I just uploaded it. As it turns out, a change to the iOS App and HA broke the trigger monitoring function in iC3. I found it yesterday while out running errands without iC3 loaded and the zone enter/exit and other triggers started coming in. 

I'm closing this issue. If you continue to have problems after RC7, please open another issue.
