### ISSUE TITLE
customization

### ISSUE THREAD

**Issue by GHSTUDIO1** [gcobb321/icloud3#43]
Installed icloud3...found my iphone....and found all of the sensors....great, everything works.  But...there are sensors I never want to deal with so I went to configuration/customization and added hidden: true to all of those entries.  Confirmed that they were saved correctly in customize.yaml.   This is the exact same procedure I used with an intelligent power plug...to eliminate sensors I didn't want to see in the overview rather than configure my own overview.  

The sensors I customized from the power plug no longer show in the overview, as expected.....the sensors I customized for my iphone still show.  I've rebooted multiple times and they still show.

Not sure if this is an issue with ios, icloud3, Hassio....(or me)...but it's inconsistent for sure.

**Comment by gcobb321** [comment]
The sensors are recreated each time iCloud3 loads when HA is restarted. This may be the reason they keep reappearing since they are not typical sensors that are defined in the configuration.yaml file. 

If this is the cause, I don't see any solution to your problem without being able to specify what sensors should be created by iCloud3. Which probably won't be done.
