### ISSUE TITLE
icloud3 generating 500 of these errors per minute: 'The see service is not supported for this entity'

### ISSUE THREAD

**Issue by deepcoder** [gcobb321/icloud3#46]
I am trying to configure icloud3 using the Home Assistant iOS app integration and I get these errors in the home-assistant.log :

'The see service is not supported for this entity'

Side note. As I understand your section on different ways to integrate icloud3 with iOS. If I understand correctly, if user has Apple's Two Factor Authentication enabled you should NOT try to use icloud3 using Apple iCloud integration. Correct? If so, I think you should just clearly state this at the beginning of your documentation and not have people go to the effort of getting to a road block several steps into your installation. FYI, I would think that a large segment of iOS users have 2FA turned on at this point, as Apple makes it difficult to avoid.

It's not clear to me how the core iOS integration can work with 2FA on and icloud3 does not.

**Comment by gcobb321** [comment]
iCloud3 v2.2.0 in the development-2.2.0rc6 directory is undergoing final 
testing and docs update does support 2fa. You can download it at 
https://github.com/gcobb321/icloud3/tree/master/development%20v2.2.0-rc6. 
Installation instructions and new features are in the Release Candidate 
Change Log.

The HA iCloud integration and the iCloud Web Service interface program 
(pyicloud.py) was updated about 1-2 months ago to support 2fa. This has 
been incorporated into iCloud3 and it's customized version of the 
support program (pyicloud_ic3.py) has been updated to support it also. 
Most of the users of iC3 were forced to use the Find-my-Friends tracking 
method because of the change Apple made requiring 2fa in the past year 
or so. It is only in the past few months that it was possible to access 
2fa accounts and the version of iC3 (v2.2.0) will be released for 
general availability shortly.

I would suggest you install the Release Candidate and use the 2fa FamShr 
tracking method since you are new to iCloud3.



------ Original Message ------

**Comment by deepcoder** [comment]
I tried the 2.2.0rc6 of icloud3, I was able to get it to successfully login to my icloud account and show states for the iphone.

Two problems however:

1) I continue to get rapid continuous of this error in the home assistant log:
ERROR (MainThread) [homeassistant.components.device_tracker] The see service is not supported for this entity device_tracker.iphonexi

This appears to be a show stopper for my configuration. 

2) The location of the 'icloud3-event-log-card.js' file seems to be hard coded in the python code to require it's location in the directory 'www/custom_cards'

**Comment by gcobb321** [comment]
The www/custom_cards is the default since that is what is in the docs and other users have used. You can put it where you want and specify your location in the Lovelace resources parameter in the HA ...  config file. The 'event_log_card' directory' parameter in iCloud3 let's you specify where you have it to do the version checking for the Event Log. I'll make that clear in the docs. 

From the change log:
`event_log_card_directory` This contains the directory used to store the iCloud3 Event Log Lovelace card. The Event Log version (icloud3-event-log-card.js) is checked when iCloud3 starts to verify the latest version is installed. If not, the version in the custom components directory is copied to the Event Log directory.
Valid values: Standard file name Default Value: 'www/custom_cards'

**Comment by gcobb321** [comment]
Re: see service error. Is that coming from iCloud3 or the iOS app? What version of HA  are you running? What are the device names you have set up for the iOS app? For iCloud3?

**Comment by deepcoder** [comment]
As to my point 1:
Thanks for clarifying your documentation on the locations of the .js file and .log files! I think your icloud log file view will be helpful to a lot of people, due to the face these configuration are complex and fragile. 

As to my point 2:
I think I had a lot of legacy entries in the follow files, due to prior attempts to use mobile phone location services. So I backed up these files and did an aggressive  removal of json entries for my iphone. I had upgrades from iPhone 10 to 11 and renaming of iPhone related entries. So far only a single error in the home-assistant.log file, however I have yet to have 'moved' my iPhone. We shall see. Thanks for your work on this useful and complex integration! 
2020-06-16 20:40:57 ERROR (MainThread) [homeassistant.components.sensor] Entity id already exists - ignoring: sensor.iphonexi_last_update_trigger. Platform mobile_app does not generate unique IDs


/home/pi/homeassistant/.storage
-rw-r--r--  1 root root   4738 Jun 16 19:18 core.config_entries
-rw-r--r--  1 root root  16056 Jun 16 20:27 core.device_registry
-rw-r--r--  1 root root  79932 Jun 16 20:39 core.entity_registry
-rw-r--r--  1 root root  24084 Jun 16 20:40 core.restore_state

/home/pi/homeassistant
-rw-r--r--  1 root root    1049 Jun 16 19:01 .ios.conf

**Comment by gcobb321** [comment]
FYI. You will find more info on the error message on the iOS App forum [here](https://community.home-assistant.io/c/mobile-apps/ios) and do a search for it. 

I posted this on the iCloud3 forum several weeks ago. 

You may see error messages similar to this when HA starts:

Entity id already exists - ignoring: sensor.gc_last_update_trigger_mobapp. Platform mobile_app does not generate unique IDs
Entity id already exists - ignoring: sensor.lc_last_update_trigger_mobapp. Platform mobile_app does not generate unique IDs
This is a known iOS App issue that has been around for a few versions and can be ignored.
