### ISSUE TITLE
Rc9 and RC8 have the same problem. Once they get Stationary, they will get stuck.

### ISSUE THREAD

**Issue by a120578270** [gcobb321/icloud3#55]
Rc9 and RC8 have the same problem. Once they get Stationary, they will get stuck.

**Comment by gcobb321** [comment]
I just took a look at one of the log files from an earlier issue. It show you are using either, using ios app v1 or do not have the ios app v2 installed). 

```
 Stage 3 > Verify tracked devices
 Verified Device > Meifeng (mei_feng_iphone)
 IOS App v1 monitoring > device_tracker.mei_feng_iphone
 Verified Device > Lm (iphone_lm)
 IOS App v1 monitoring > device_tracker.iphone_lm
 Verified Device > 6Gongzuoji (iphone6gong_zuo_ji)
 IOS App v1 monitoring > device_tracker.iphone6gong_zuo_ji
 Verified Device > Lb (iphone_lb)
 IOS App v1 monitoring > device_tracker.iphone_lb
 Tracking Devices >  mei_feng_iphone, iphone_lm, iphone6gong_zuo_ji, iphone_lb
```
iCloud3 relies on the ios app to issue Region Enter/Exit triggers that put the phone in a zone and take it out of the zone. More info about that is [here](https://gcobb321.github.io/icloud3_docs/#/chapters/1-setting-up-icloud-account?id=what-if-i-don39t-have-the-ha-ios-companion-app-on-my-device).

1. Do you have the ios App installed? What version?
2. If yes, are you getting Region Enter/Exit events? If no, see the docs above on how that is handled.
3. Does the iC3 Event Log show these events?
4. If yes, are they being Discarded? If so, what is the reason?
5. On the iC3 Event Log screen, press Debug, then press Restart-iC3. You will start seeing detailed debug into in the Event Log and in the HA Log.
6. Take screen shots of when you think you should be exiting the Stat (and other) Zones. Post them here with the HA log file or send them to geekstergary@gmail.com and I'll see if I can tell what is going on.

I suspect it is because of not monitoring the correct device_tracker entities for the ios App and not getting the enter/exit triggers.

**Comment by a120578270** [comment]
I don't know whether the ios app you mentioned refers to HA's app or the ios built-in search app! None of the devices I used with ICloud3 had HA apps installed! If it is an HA app, I did not install HA in the previous 2.1 version of the app can be used normally!

**Comment by gcobb321** [comment]
That is the problem then. See the HA iOS  Companion app documentation [here](https://companion.home-assistant.io/docs/getting_started/getting-started/).

**Comment by a120578270** [comment]
According to your statement, must HA's apps be installed in all devices of icloud3? What method can do not install also can use normally?

**Comment by gcobb321** [comment]
Yes, they must be installed on each device. It is the ios app on the device that determines when that device enters/exit zones and sends location to HA & icloud3. They may all be part of the same Family Sharing List on the iCloud account but that has nothing to do with the ios app on the device.
