### ISSUE TITLE
All devices aren't being found

### ISSUE THREAD

**Issue by mar005** [gcobb321/icloud3#59]
I can't see my stepdad's iphone yet i can see my mom's iphone. What could be happening?

**Comment by mar005** [comment]
Is the reason for not finding all devices that are part of the find my friends due to the fact that the non-beta doesn't have this capability?

**Comment by gcobb321** [comment]
Yes. The beta supports Find-my-Friends where v1.0.6 does not. V1.0.6 added support for tracking using only the iOS app to get around the constant notifications created by Apple changing the way Find my Phone works. The beta changed the default tracking method, along with a lot of new features. 

I expected to have it out about a month ago but decided to add support for iOS app v2 before I released it since, at the time, it had been submitted to Apple for approval And was expected to be released very soon. We are still waitinG. Then a 3 week trip and a computer crash that took this past week to get everything back to normal. Look for a 'release candidate's sometime next week after I complete some 'stress testing' and documentation.

**Comment by mar005** [comment]
What’s is weird is that it did find my mom’s phone and I didn’t setup the beta only the released version. Perhaps I should have been more thorough when I opened my issue. That is what is weird
