### ISSUE TITLE
Tracking never switches from 'stationary' to a known zone

### ISSUE THREAD

**Issue by jcollas** [gcobb321/icloud3#6]
icloud3 - 2.0.1

Things are stable and not throwing exceptions, but I've noticed that when people return home, they are marked as stationary, and never switch to 'home', (or any of the other known zones).  This prevents several automations from running correctly.

**Comment by gcobb321** [comment]
I don’t have any issues switching to home when I arrive but you have a lot more zones than I do. I’m wondering if you are going from a stationary zone to home. Post your zone.yaml file and I’ll try to make my zones look like it To see if I can duplicate the problem. 

Btw, I’m headed out of the country this Sunday and won’t return until late January. Would be nice to get it fixed before I leave. I will be uploading one more update this week for another issue and want to roll this fix into that update.

**Comment by gcobb321** [comment]
I just uploaded an update to fix this. The description is:
- If the device_tracker.state is 'stationary' when the next update time is reached and you have moved into another zone that is not stationary, the 'zone' attribute is correct because it is based on the device's location values but the device_tracker.state is still 'stationary' instead of the zone the device is now in. This has been fixed.

It is in the [Prerelease directory](https://github.com/gcobb321/icloud3/tree/master/prerelease). 

Let me know if you still have an issue or if this takes care of the problem since I can not duplicate it on my end.

**Comment by jcollas** [comment]
Testing now.  I have two people away, when they return home and automations run, I'll update you.  Thanks for all your hard work on this.

**Comment by gcobb321** [comment]
I just posted another update to the state/zone issue. There are now 2 versions of the update for you to test.
v2.0.2-zonecheck1 - (The one you already have) Deals with state=stationary and zone=a non-stationary zone. The state is changed to the zone value.
v2.0.2-zonechedk2 - Deals with state=a zone (stationary or something else) and zone=a different zone. The state is changed to the zone value.

My current thinking. Since the code has been the old way for a long long time, I am reluctant to move it into the main branch before I go away for 7-weeks. I will promote v2.0.2 tomorrow and hold off on the zonecheck versions in case something doesn't work correctly. You would be fine running the special version and would have the options of using others. Plus, I will be able to make minor changes to the code without affecting others.

**Comment by jcollas** [comment]
I think that's a good strategy.  Never do a release build on Friday kind of thing.  I've been running your version, and it appears to be working well.  People who return home are now changing state properly.  Since you've made some choices available, I'll be happy to try them out over the next few weeks, and I'll have more information for you to work with when you return.  Happy travels, and happy holidays!

**Comment by gcobb321** [comment]
I have uploaded new versions of the v2.0.2-zonecheck 1 and 2 for you to try. I have installed them in the icloud3_dev/prereleases repository to keep the base icloud3 clean with the latest v2.0.2 update. The changes include some reformatting of Event Log messages that are in the main release and the addition of Event Log items when it detects the issues you are dealing with. I'm not sure of your background but the code is inside the '###############' lines at 4277-4303 in the '_update_device_attributes' function in device_tracker_xxx.py. The device_tracker.py is the zc2 version.

You can find the special versions in the [iCloud3_dev repository here](https://github.com/gcobb321/icloud3_dev/tree/master/prerelease).

**Comment by gcobb321** [comment]
i have just uploaded v2.0.4 which I think takes care of your problems permanently. The change log includes:
- When the device's location, interval and next poll information were being updated, there were times when the state was 'stationary' but it had actually moved into another zone. This might be caused by zones being close together, by no zone exit notification from the ios app or by the next update trigger being processed before the zone exit trigger had been received. This caused the device's location to be reset to the old location instead of the new location. This has been fixed.
- Waze history data is used to avoid calling Waze for route information when you are near another device or in a stationary zone with accurate Waze route information. If you were in a stationary zone and entered another zone without a zone exit trigger, the Waze history was still pointing to the old stationary zone. The old location information was being used for distance and interval calculations instead of the new location information.  A check was added to always refresh the Waze route information when the state changes.

[device_tracker v2.0.4.zip](https://github.com/gcobb321/icloud3/files/3906174/device_tracker.v2.0.4.zip)

**Comment by jcollas** [comment]
Testing now.  Although 2.0.3 seemed pretty reasonable.

**Comment by broyuken** [comment]
I'm having a similar issue where my devices never go into a stationary zone, it will just show me as away no matter how long I stay somewhere.
