### ISSUE TITLE
iCloud3 not updating when I enter home zone until hours after I am actually home

### ISSUE THREAD

**Issue by ThrashinVictim** [gcobb321/icloud3#60]
I have version 2.2.0.04rc10 of Icloud3 and 2020.4.1 of HA IOS app.

The problem I am running into is that Icloud3 does not pull my correct location when I enter home zone. 
But hours later it says that I finally enter home zone.

For example today.

I got home at 5:45pm. I have an automation that turns my lights on when I arrive home but only after dusk. Icloud3 updated my position at 10:13 causing the automation to fire, but I had already been home for almost 5 hours. 

Is there any settings that I need to change to fix this issue? 

Thank you.

**Comment by MikeTannenbaum** [comment]
I'm new to icloud3 but if you haven't seen these docs with all the config settings you should take a look: https://gcobb321.github.io/icloud3/#/chapters/2-config-parms

They let you change the intervals for updates based on whether the device is in a zone or out, within a stationary zone or outside, and so on.

I'd play with that and see if you can get what you're looking for and if not pop back here.

Hope that helps!

**Comment by gcobb321** [comment]
Some of the iOS App updates may be creating duplicate device_tracker entities. I believe the release candidate you are running stops looking for the device_tracker entity to monitor when it finds the first one. That has been changed to look for the last one. It also lists all the entities it finds, reports duplicates and instructs you how to force select the entity to be tracked. There have also been a lot of other changes since RC4 (now RC11).

For more info, how to download it, and how to install it, go [here ](https://community.home-assistant.io/t/icloud3-v2-1-device-tracker-advanced-tracking-features-ios-app-monitoring/148943/552).

**Comment by ThrashinVictim** [comment]
I updated to RC11. I did see an error saying I need to change the name in HA

The Device Name on the phone must be the same as the iOS App device_tracker being monitored.,  1. Open the iOS App on the phone.,  2. Select HA Sidebar>General.,  3. Change the Device Name on the phone to mobile_app_liams_iphone_1.,  4. Close, unload and restart the iOS App on the phone to send the new Device Name to HA.,  5. Restart HA.  
I renamed the app to mobile_app_liams_iphone_1 but still get that error.

**Comment by MikeTannenbaum** [comment]
I'm getting this same error and also made the change on device but still having the error

**Comment by gcobb321** [comment]
@liamrpower, @mikeTannenbaum
 iCloud3 adds “mobile_app” to the device name before sending the request to the phone so you don’t also need it on the phone. Doing that probably lead HA to add it to the entity name which would then send the request to “mobile_app_mobile_app_liams_ipaone_1”.

 Change the Device Name on the phone to liams_iphone_1. HA may have also changed your device_tracker entity name and added the mobile_app to it too. You may have to change the device tracker entity name on the Configuration > Device, Entities or Integrations screen. 

I’ll correct the message being displayed

Thanks

**Comment by MikeTannenbaum** [comment]
Changed it back to the device names `mikeys_iphone_hassio` and `arielles_iphone_hassio` — those are the names within iOS Settings and the HA app, as well as what's added to `configuration.yaml` for device_tracker with iCloud3.

Right now the only `device_tracker` entities I have are these two, which are coming from the Mobile App. Am I correct that iCloud3 should be adding its own entity for each device I'm tracking? If so, I'm not sure where the hangup is.

<img width="958" alt="Screen Shot 2020-08-18 at 10 46 47 AM" src="https://user-images.githubusercontent.com/792648/90527987-200b7600-e140-11ea-90ee-370a01fc5184.png">

EDIT: Including device names across apps
`configuration.yaml`
<img width="330" alt="Screen Shot 2020-08-18 at 10 50 01 AM" src="https://user-images.githubusercontent.com/792648/90528410-94deb000-e140-11ea-93b8-4071000733b5.png">

`iOS Settings`
![image](https://user-images.githubusercontent.com/792648/90528774-0159af00-e141-11ea-9b33-95f7682ebdf7.png)

`HA app`
![image](https://user-images.githubusercontent.com/792648/90528935-29e1a900-e141-11ea-8acf-3ddef87d5f8a.png)

```
Logger: custom_components.icloud3.device_tracker
Source: custom_components/icloud3/device_tracker.py:7931
Integration: icloud3 (documentation)
First occurred: 10:36:57 AM (4 occurrences)
Last logged: 10:37:15 AM

iCloud3 Error > Error sending test msg to Mikeyshassio (mikeys_iphone_hassio) > Device-`mikeys_iphone_hassio`, Error-Unable to find service notify/mobile_app_mikeys_iphone_hassio. -------------------------. The Device Name on the phone must be the same as the iOS App device_tracker being monitored. Select the correct device_tracker entity or do the following to change the Device Name on the phone.. 1. Open the iOS App on the phone.. 2. Select HA Sidebar>General.. 3. Change the Device Name on the phone to `mobile_app_mikeys_iphone_hassio`.. 4. Close, unload and restart the iOS App on the phone to send the new Device Name to HA.. 5. Restart HA.
iCloud3 Error > Error sending test msg to Arielleshassio (arielles_iphone_hassio) > Device-`arielles_iphone_hassio`, Error-Unable to find service notify/mobile_app_arielles_iphone_hassio. -------------------------. The Device Name on the phone must be the same as the iOS App device_tracker being monitored. Select the correct device_tracker entity or do the following to change the Device Name on the phone.. 1. Open the iOS App on the phone.. 2. Select HA Sidebar>General.. 3. Change the Device Name on the phone to `mobile_app_arielles_iphone_hassio`.. 4. Close, unload and restart the iOS App on the phone to send the new Device Name to HA.. 5. Restart HA.
iCloud3 Error > Mikeyshassio (mikeys_iphone_hassio), mikeys_iphone_hassio > iOS App Entity device_tracker.mikeys_iphone_hassio does not contain location attributes (latitude, longitude). iCloud3 will be restarted in the 10 minutes if this error continues.. -------------------------. Attributus-not_set, {}
iCloud3 Error > Arielleshassio (arielles_iphone_hassio), arielles_iphone_hassio > iOS App Entity device_tracker.arielles_iphone_hassio does not contain location attributes (latitude, longitude). iCloud3 will be restarted in the 10 minutes if this error continues.. -------------------------. Attributus-not_set, {}
```

**Comment by MikeTannenbaum** [comment]
I'm also confused because when I first had it installed I saw so much information within the device_tracker entity, but now I'm seeing only the basics, which makes me think something isn't working correctly

<img width="378" alt="Screen Shot 2020-08-18 at 11 02 55 AM" src="https://user-images.githubusercontent.com/792648/90530249-a6c15280-e142-11ea-9b37-97c85cb0a00a.png">

**Comment by gcobb321** [comment]
The track_devices names must match the iPhone SettingsApp>General>Phone Name. The iosApp Device Name must match the mobile_integration device_tracker name.

```
track_devices:
  - mikeys_iphone > mike.jpg
  - arielles_iphone > arielle.jpg  
```
iOS App Device Name=mikeys_iphone_hassio  (or Mikeys-iPhone_Hassio)
mobile_app device tracker=device_tracker.mikeys_iphone_hassio 

iOS App Device Name=arielles_iphone_hassio  (or Arielles-iPhone_Hassio)
mobile_app device tracker=device_tracker.arielles_iphone_hassio 

The v2.2.0 docs explains this a little better than the old docs. Plus, some (a lot) of the iOS App and mobile integrations/entities changed since v2.1.0.

Would you review the v2.2.0 docs and see if it clearly explains how it should be set up and let me know if there are any changes I should make to improve the explanation to avoid confusion?. Thanks.

v2.2.0 docs are in the Gettig Started chapter [here](https://gcobb321.github.io/icloud3_docs/#/chapters/1-getting-started)

**Comment by MikeTannenbaum** [comment]
@gcobb321 thanks for that — I now see the ic3 device_tracker and the Mobile App one, so that's working. The data within the tracker isn't there though, which confuses me. Also I can't tell why the ic3 device_tracker now shows "not set" at the top, when I'm sitting in my home connected to wifi which is within the zone of HA.

<img width="313" alt="Screen Shot 2020-08-18 at 2 04 39 PM" src="https://user-images.githubusercontent.com/792648/90549004-d6c91f80-e15b-11ea-8abc-5f4f570e09e9.png">


<img width="477" alt="Screen Shot 2020-08-18 at 2 07 02 PM" src="https://user-images.githubusercontent.com/792648/90549177-198af780-e15c-11ea-962b-10a683cff2bb.png">

regarding docs, my point of confusion as I read them all super carefully was that I thought ALL devices needed to be the same name. I now see they don't. but I think a tl;dr style sentence that says something like "ic3 device name should match `track_devices` and Mobile App Device Name should match `device_tracker` name within HA entities" woud make it more clear. Written a little better, but that shows that there are two different device names: 1) HA Mobile App within HA Entities and 2) `track_devices` + `iOS Device Name`. I was thinking they all needed to be the same. In hindsight it makes sense they don't, but somehow while reading through I ended up changing them all to be the same as that's what errors/docs/etc led me to think was right.

EDIT: I removed my iphone from the Mobile App integration w/in HA, killed the app, reloaded it, and restarted ic3 and am coming up with the same as above. Just letting you know in case that was your suggestion! I'm running out now but hope to get back to this later. Taking a long time to get this operational (days) but I'm getting there!

**Comment by MikeTannenbaum** [comment]
I might have it resolved...I'm on the go and was able to get it to update by restarting everything. Will see how this trip goes and if it updates when I get back to my home zone. Just wanted to let you know. I'll post again either way just to help close this out.

**Comment by ThrashinVictim** [comment]
Thanks for all the info. With both of your guy's help, I was able to fix the problem.

**Comment by liamrpowell** [comment]
I noticed I had to name it liams_iphone_1 as liams_iphone was taken already. Is that normal?

**Comment by gcobb321** [comment]
I’ve received several emails from both of you and am confused as to whether you are still having problems. But...

The phone’s name and the track _devices name must be the same. The iOS app mobile_app Integration device _tracker entity must be the the same as the track devices name with a suffix.

Example:
Phone name = Gary-iPhone
track_devices = gary_iphone
mobile_app entity = gary_iohone_app (or _1 or _hassio)

I’m going to close out all the email messages. Let me know if you are still having problems.

**Comment by MikeTannenbaum** [comment]
I am all good for the moment! Can't close the github comment but have been able to get everything working well.
