### ISSUE TITLE
How does this interact with the mobile_app HA iOS beta

### ISSUE THREAD

**Issue by mar005** [gcobb321/icloud3#60]
I have the beta HA iOS app on my phone, and when I hooked up this app i expected a duplicate iphone device_tracker yet I do not see one. I only found my mom's iphone which is weird.

**Comment by mar005** [comment]
I'm seeing this error with my phone

`The see service is not supported for this entity device_tracker.miguel_iphone`

**Comment by gcobb321** [comment]
There were so many changes to the way the beta worked that I haven't consecrated on making iCloud3 easily compatible. The biggest change is the device names are no longer specified on the device but assigned in a numerical order based on when they were added to HA (I.e., miguel_iphone_2).. . 

It seems that to tie everything together and link the tracked device name with the name assigned, you have to rename the device_tracker with the number to the one you set up on the settings>general>about screen on the iPhone (I..e, Miguel-iPhone). The above error is probably because the HA doesn't think the miguel_iphone is a device since the one created by the iosapp ends with _#.

The log file lists what device's are being tracked when it starts up. BTW, the method of specifing device's is changing on the next release. See the code and readme docs in the beta directory.

**Comment by mar005** [comment]
Thanks I ended up changing my name and it fixed it. Now I wonder also if you’re suggesting I just try the beta that you made for icloud3?

**Comment by gcobb321** [comment]
Yes but I'll be putting up a new version of the beta probably late today or tomorrow.

**Comment by mar005** [comment]
I have a question after reading your readme that perhaps is obvious but I missed it when I first read it. Does this component join both the device trackers so that you should only have 1 device tracker that has both information? I currently have ios HA v2 beta and that one gives me 15 sensors that are not named as you would expect with a prefix of miguel_iphone they just have like sensor.activity and the device tracker for that is miguel_iphone_x. Then i have the icloud3 (non beta -> currently trying to understand icloud3 beta on how it works) which creates about 34 sensors each with miguel_iphone_blah.

Reading your readme where you need to indicate iov2app (something like this) I felt that perhaps I am suppose to have 1 device_tracker that is miguel_iphone and not two like I have right now?

**Comment by gcobb321** [comment]
It depends. 
IOS App v1 - If your phone name is Miguel-iPhone which converts to 'miguel_iphone' and is tracked with device_tracker.miguel_iphone entity. The IOS App v1 uses this entity and it is monitored by iCloud3. iCloud3 adds a lot of attributes to device_tracker.miguel_iphonebut they coexist together.

IOS App v2 - This version is different. If 'device_tracker.miguel_iphone' does not exist, it will create it. If it does, it will append a number creating a unique entity, i.e., 'device_tracker.miguel_iphone_2'. The entity will not exist if iCloud3 or IOS App v1 has not been tracking the device using the 'device_tracker.miguel_iphone' entity. Additionally, v1 uses the device_tracker entity for its zone enter, zone exit, background fetch, significant location change and other triggers. v2 uses the 'sensor.last_update_trigger' entity to store this information. If you have several phones, there will be sensor.last_update_trigger_2, _3, etc. 

iCloud3 v2 (soon to be released) handles both situations. When it starts, it scans the '.storage/core.entity_registry' file for a device_tracker entity starting with the device's name (miguel_iphone). It picks up the prefix number, if it exists and  then searches for the sensor.last_update_trigger entity associated with that device_tracker to get the zone and movement triggers.

Hope this helps. The beta version and docs out there right now do not look at the entity registry file  to get the correct devices to monitor. I finished the coding to do this about a week ago.

I need to redo the docs, test 2 more items and then I'll release it as iCloud3 Version 2.0
