### ISSUE TITLE
2.20 After the HA version of RC11e is restarted, the acquired location will become Home

### ISSUE THREAD

**Issue by a120578270** [gcobb321/icloud3#69]
HA gets the location right at the beginning of the restart and then becomes the home location after a few seconds, and then after a few more seconds it returns to normal

![image](https://user-images.githubusercontent.com/58241282/91381795-cd763c00-e85a-11ea-94fc-8661cc9493f7.png)
![image](https://user-images.githubusercontent.com/58241282/91381813-d830d100-e85a-11ea-87fa-148f5cc7372f.png)
![image](https://user-images.githubusercontent.com/58241282/91381827-dff07580-e85a-11ea-900c-0b0b3e52ada6.png)

**Comment by gcobb321** [comment]
It looks like there were 2ios app state changes (11:34:35 and 11:34:49) that were issued by the iOS app during the initial locate, also a gps error and several discarded triggers. The iOS app was putting the phone into the stationary base zone which was also discarded. Finally iCloud got a good location and things corrected themselves. It probably started with the initial iOS state changes caused by the iOS app. 

I also noticed several other things:
1. The distance shown is miles instead of km. You can use the *unit_of_measurement: km* parameter to switch to km
2. The phone is using an older version of the Event Log. To refresh the phones cache, on the phone, go to HA Sidebar> AppConfiguration (at the bottom)  > Refresh Browser Cache (at the bottom). Then swipe down the screen to refresh the app data (spinning wheel is displayed). 
3. On the event log, the Actions pull down has a Show Event Log details. It will display detailed info about the iOS app data received and helps in figuring out what is going on

**Comment by gcobb321** [comment]
HA seems to load iCloud3 before the mobile_app so the iOS App location is not available when iC3 starts. RC12b will try to get the iOS App location when it starts (and restarts using the *Event Log > Actions* Restart option). If the iOS App location is available, it will be used, otherwise, the Home location is used to seed the attributes during initialization.
