### ISSUE TITLE
Doesn't install right from HACS

### ISSUE THREAD

**Issue by broyuken** [gcobb321/icloud3#7]
I'm trying to install this from HACS, but it doesn't seem to download all the right files. I'm not getting the hacs.json, device_tracker.py or most of the other files. I only get the few listed below.

core-ssh:/config# ls -l /config/custom_components/icloud3/
total 84
-rw-r--r--    1 root     root            29 Nov 25 16:17 __init__.py
-rw-r--r--    1 root     root         33930 Nov 25 16:17 icloud3-event-log-card.js
-rw-r--r--    1 root     root          6076 Nov 25 16:17 icloud3-event-log-card.js.gz
-rw-r--r--    1 root     root           196 Nov 25 16:17 manifest.json
-rw-r--r--    1 root     root         16470 Nov 25 16:17 sample_automations_scripts.zip
-rw-r--r--    1 root     root          5865 Nov 25 16:17 sample_lovelace_cards.zip
-rw-r--r--    1 root     root          1818 Nov 25 16:17 services.yaml
core-ssh:/config#

**Comment by gcobb321** [comment]
HACS has been a nightmare the last 2 days. Installing in wrong directories, not installing everything, trashing settings and the IOS app integration. I did so much testing that my SD card was fried.

I would suggest you download it from the Releases tab on the iCloud3 repository until I figure out what is going on.

**Comment by broyuken** [comment]
I did that and it's at least loading now. I don't know what happened since I moved to the beta companion app and v2 of icloud3 but I don't think I can use it. I have 2FA on my icloud account and for my HA account and have for months now. It appears now that I can't use an account with 2FA without getting spammed every 30 minutes (which isn't even happening because I get this error

```
2019-11-25 22:40:42 ERROR (SyncWorker_1) [custom_components.icloud3.device_tracker] iCloud3 Error: Setup aborted for Group-family, Username-brianroy86@gmail.com. No devices to track.
```

Before I upgraded these I was using iCloud3 without spam, and it seemed to work great up until a few days ago, not sure what happened because this was way after when you said apple was signing people out every 30 minutes back in June. I didn't even have iCloud3 installed until probably August. 

Whatever happened, please revert it so this can actually be used by people who have 2FA on their accounts. I'm not going to create a dummy apple id just to get this working again, I'll just stick with the mobile_app integration if that's the only option.

**Comment by gcobb321** [comment]
Devices that are tracked in iCloud3 v2 have to be specified by the actual devicename instead of by scanning the devices tied to the iCloud account. This is done with the ‘track_devices’ parameter. The error message you listed indicates you don’t have that parameter in the config file or the devicename entry you have cannot be found if the iCloud account. 

There is a section in the documentation [here](https://gcobb321.github.io/icloud3/#/chapters/1-setting-up-icloud-account)  That I’m sure you have read that talks about 2fa accounts and how Apple changed the way the they they log you out every 30-minutes or so. I was also perfectly happy the way it was and did not really want to make the changes to support the FmF method of tracking devices. The choice was simple. Do it and set up a dummy non-2fa account or throw iCloud3 away. 

There is no reverting back to the way it was because of the change in the way Apple secures accounts. Since you’re a not going to create the dummy non-2fa account, good luck with just using the mobile app.
