### ISSUE TITLE
2FA authentication not working

### ISSUE THREAD

**Issue by bobvmierlo** [gcobb321/icloud3#80]
I just changed my username and password to my 'normal' 2FA account since this is working since v2.0
The initial authentication works fine, but after the 1st icloud update this doesn't work and needs to be verified again. And this needs to be verified on every icloud update. So this would mean i would have to verify the 2FA every hour.

I get to following error in the event log:
iCloud Alert>Apple/iCloud Account Verification Required > Open HA Notifications window to select Trusted Device and to enter the 6-digit Verification Code.

I allready tried removing the old cookie to start with a fresh account. This does not solve the issue.
For now I've reverted back to the non 2FA account that I used before. But it would be great if this could be fixed.

**Comment by schumi2309** [comment]
i have the probleme too !!!!

**Comment by gcobb321** [comment]
Have you completed the authentication process where you select the phone to receive the 6-digit code via a text message and then entered that code in the Enter Verification Code window described in the iCloud3 docs [here](https://gcobb321.github.io/icloud3/#/chapters/1-getting-started?id=how-to-authenticate-your-icloud-account)?

**Comment by schumi2309** [comment]
i have not a windows code verification in HA !
but i receive the 6-digit code.

**Comment by gcobb321** [comment]
The iCloud3 docs describe the windows you will see, the window Apple sends that can be ignored and why, how to do the authentication and how to force the authentication request. All the information is described [here](https://gcobb321.github.io/icloud3/#/chapters/1-getting-started?id=authenticating-your-icloud-account).

**Comment by bobvmierlo** [comment]
> Have you completed the authentication process where you select the phone to receive the 6-digit code via a text message and then entered that code in the Enter Verification Code window described in the iCloud3 docs [here](https://gcobb321.github.io/icloud3/#/chapters/1-getting-started?id=how-to-authenticate-your-icloud-account)?

Everything works perfectly fine, even the 6 digit code in the SMS. But the problem is that every hour when icloud3 requests the new location from Apple I get a new notification in HA to configure again. And I keep getting the notifications on my phone that someone is trying to log in.
Meaning that what you describe about having to redo those steps every 2 months or so, happens every hour. (or if you like, everytime iCloud3 pulls information from Apple)

**Comment by gcobb321** [comment]
After you enter the code  in the Enter Verification Code window, the cookie file described in the docs should be getting updated with an expiration date a few months from now. There may be some messages in the HA Log file that show the activity taking place during the verification process. Review the file and see if anything shows up right after you do the verification.

**Comment by bobvmierlo** [comment]
Hmm.. after deleting the cookie for the 3th time and restarting HA for the 3th time the authentication seems to be registered properly now. I can also see good expiration dates and I'm not getting any new notifications now.
Not sure what the issue was though..

**Comment by gcobb321** [comment]
I just deleted my cookie file to verify the process (it's been a while since I did it). The code was entered and verified but then was getting a no location returned (GPS-(0, 0)/0) a few times. I restarted iCloud3 from the Event Log > Action pulldown and the correct location was returned and the verification was completed.

Communication with Apple Servers can act strange t times. Glad your now verified.

**Comment by avd706** [comment]
I got it to work by accessing home assistant with chrome browser  on PC (won't work with ios app which uses safari) and use the number pad to select the device. Crazy? On Oct 9, 2020 15:08, Gary Cobb <notifications@github.com> wrote:
I just deleted my cookie file to verify the process (it's been a while since I did it). The code was entered and verified but then was getting a no location returned (GPS-(0, 0)/0) a few times. I restarted iCloud3 from the Event Log > Action pulldown and the correct location was returned and the verification was completed.
Communication with Apple Servers can act strange t times. Glad your now verified.

**Comment by bobvmierlo** [comment]
Unfortunately the issue represents itself after a few hours. Even though the cookies are far from being expired the integration keeps forcing me to reconfigure the 2FA every few hours.

FYI: the location updates do still work even when I don't reconfigure. So somehow the cookies seem to do their work and I do get new information from the Apple servers. But in HA the configure notifications keeps popping up and I keep getting the notifcations on my iPhone.

**Comment by gcobb321** [comment]
When an authentication is needed, the iCloud interface, pyicloud-ic3.py, generates an Error 450 or 500 that will be in the HA log file and on the *Configuration > Logs* screen. Do you see that? The Event Log shows when an authentication is done and if it was successful or not. Does that show anything? What happens if you restart iCloud3 from *Event Log > Actions*?

**Comment by bobvmierlo** [comment]
Below are the error's from the HA log and the event log.
And by now I have 13 open standing notifications in HA to configure the 2FA. 

The integration stops retrieving the location from Apple, but when I do a restart from the actions in the eventlog card the integration does succesfully retrieve the location. However after the 1st interval it starts throwing the account verification error and it stops retrieving the location.

```
Logger: custom_components.icloud3.device_tracker
Source: custom_components/icloud3/device_tracker.py:8171
Integration: icloud3 (documentation)
First occurred: 2:59:00 AM (10 occurrences)
Last logged: 8:33:00 AM

Bob (iphone) iCloud3 Error > The iCloud 2fa code for account REDACTED needs to be verified. Use the HA Notifications area on the HA Sidebar at the bottom the HA main screen.
Annelinde (iphone) iCloud3 Error > The iCloud 2fa code for account REDACTED needs to be verified. Use the HA Notifications area on the HA Sidebar at the bottom the HA main screen.
```

![image](https://user-images.githubusercontent.com/38190383/95714223-2f063480-0c68-11eb-9a52-828db1fbd537.png)

**Comment by gcobb321** [comment]
I've created another issue on this subject with guidance on what to do. It's [here](https://github.com/gcobb321/icloud3/issues/83).
