### ISSUE TITLE
v2.2.0 reverted yamllint fixups

### ISSUE THREAD

**Issue by darknicht66** [gcobb321/icloud3#86]
It appears that the update to v2.2 has reverted the yamllint fixups I had added previously. All the errors in the sample automation code are back as well as in a few other areas.

I can go back through and re-apply the fixups, but is there a location that I missed updating previously that caused the reversion? I'd like to try to avoid another reversion on the next update.

BTW, I'm still loving this integration. It works amazingly well.

**Comment by gcobb321** [comment]
What are the names of the files you changed? If they are the sample files, you should rename those files to something else and then update the new ones. The files with sample in the names will be updated on each new release. 

You also need to move them out of the iCloud3 directory. When I tested the HACS update, I was surprised, and not in a good way, that HACS deletes everything in the iCloud3 directory and then installs the new files.

**Comment by darknicht66** [comment]
Apologies. I should have been more clear. What I meant was that the v2.2 merge reverted commit a587a68 which I had previously submitted in pull request #30 . I looks like the sample automation files you used in the dev branch for v2.2 were from prior to the committed sample automation files in master. 

I can fixup the files again and re-submit a pull request for them, but I'd like to ensure that master and dev get in sync with each other so that they don't get wiped out again on the next dev->master merge. If I submit against master, will the changes get picked up in your current dev work?

**Comment by gcobb321** [comment]
The master is actually on my computer, not GitHub since I am the only developer of there project. Typically, I do not do a pull request before doing an update. And I made some changes which would have override what you did without knowing/remembering it. 

Go ahead and fix up the files again and rather than issuing a pull request, let’s do it old school and email them to me to make sure my master gets updated. Send them to  geekstergary@gmail.com. Then they will get into the v2.2.1 update to be released as soon as I add a little code to the iosapp tracking method routines to mirror the iCloud tracking method when the iCloud verification stops working.

**Comment by darknicht66** [comment]
Sounds like a plan. I'll roll through the updates in the next few days as I get some time and then email them over to you.

**Comment by darknicht66** [comment]
Attached are the cleaned yaml files. I'll also send them to you directly via email.

[icloud3-yamllint-fixup.zip](https://github.com/gcobb321/icloud3/files/5431069/icloud3-yamllint-fixup.zip)

**Comment by gcobb321** [comment]
I have updated GitHub and the master files on my system. Thanks.

------ Original Message ------
