### ISSUE TITLE
Version 2.2.1 is shown as Away when the location is Away

### ISSUE THREAD

**Issue by a120578270** [gcobb321/icloud3#90]
The previous version will be shown in Chinese. The new parameter setting display_zone_fname: True is also not translated in 2.2.1
![image](https://user-images.githubusercontent.com/58241282/97957112-4b1f7080-1de5-11eb-9928-b6c7e46c66ae.png)

The previous version will be displayed as
![image](https://user-images.githubusercontent.com/58241282/97957149-65594e80-1de5-11eb-849a-9256c682884a.png)

**Comment by mariwing** [comment]
To add to this; there is something wrong with the usage of home zone. Instead of setting a generic status "home" it seems that the component are using a string/name "Home". This has side effects like breaking the group "beboere" as you can see in the top of the screenshot. The group consist of three people that are all "home" but since the component now sets "Home" the group is displayed as not home (Borte means away in Norwegian). 

Second part of screenshot show that the iOS app device tracker reports "home" (which is translated into "Hjemme" which is Norwegian for home but the icloud3 device tracker shows "Home". To me this indicates that iCloud sets a zone name of Home instead of the generic "home". 

I hope you can understand my explanation 🤔

![image](https://user-images.githubusercontent.com/5949497/97962728-0f20e700-1db6-11eb-868a-348ff338a90d.jpeg)

**Comment by a120578270** [comment]
I see that all other areas have been translated, but only Away has not been translated

**Comment by B-Hartley** [comment]
I am seeing a problem like this (I think).
My location is reported as "Home" instead of "home".
This is breaking my "is anyone at home" group.
The group is not showing as "home" as no items in the group are "home".

Hope that makes sense.

Thanks

**Comment by broyuken** [comment]
> I am seeing a problem like this (I think).
> My location is reported as "Home" instead of "home".
> This is breaking my "is anyone at home" group.
> The group is not showing as "home" as no items in the group are "home".
> 
> Hope that makes sense.
> 
> Thanks

This! I need to roll back until this is resolved.

**Comment by broyuken** [comment]
Update: Rolling back to 2.2 works and fixes the issue. Waiting for 2.2.2 now :)

**Comment by gcobb321** [comment]
I've uploaded the fixed version to the iC3 development_directory [here](https://github.com/gcobb321/icloud3/tree/master/development_area).

Download the zip file, unzip it into the iCloud3 directory and restart HA. 

I also made a change to the icons on the Event Log so that will automaticaly be copied to the www/custom_cards directory. Refresh the iOS App and your browser to reload the Event Log (visual only, no functional changes).

**Comment by gcobb321** [comment]
Let me know if everything works on your end and then I'll update the master files on HACS.

**Comment by mariwing** [comment]
This fixed my issue, the value is correctly localized and my group of people are again home as well. Thank you very much for such a quick fix, you're awesome :)

**Comment by gcobb321** [comment]
Fixed in v2.2.1a
