### ISSUE TITLE
Extreme polling still an issue even on latest release

### ISSUE THREAD

**Issue by 26tajeen** [gcobb321/icloud3#91]
[123.zip](https://github.com/gcobb321/icloud3/files/5488932/123.zip)

MP4 video attached wrapped up in a zip file to appease github. But basically it's still doing the thing I reported in issue #85

**Comment by gcobb321** [comment]
I just turned off my phone and, since I was in the home zone when HA was running, when HA started, it refreshed my location to Home. It went through the normal polling, keeping me in Home on the normal inzone_interval update time. Restarting HA didn't get me into the 5-sec error loop like it did before. The last_located  age on the Event Log Results did grow but that is to be expected. I may add another check that when the last_located age becomes 3 times the inzone_interval, it will go into the standard error timing routines (15-sec for 4 tries, 1-min at 4 tries, 5-min at 4 retries, 30-min at 4 retries, then 60-min, then 2-hrs)

I couldn't tell anything with the video. If you think you are still having a problem, export the event log on the Event Log > Actions > Export Event Log and email the /config/icloud3-event-log.log file to geekstergary@gmail.com. Then I can see what is going on on your system and maybe able to see what the problem is.

**Comment by 26tajeen** [comment]
Ah. My wife's phone was in an 'away' zone when HA was restarted and her phone battery was flat at that point too.

Anyway I've done all I can to highlight this (minor) bug and I'll leave it there. Thanks for the fantastic tracker that is iCloud3! :-) :-)

**Comment by gcobb321** [comment]
This should be fixed now. Reopen the issue is you find a problem. Release Candidate 7 was just uploaded.
